// Seam under test: TRAC_IK::TRAC_IK::CartToJnt on a KDL chain built from a URDF string.
// Assertions are structural on purpose: the solver's RNG is not seedable until ticket 10, so no test
// may expect a particular configuration. What must hold for ANY valid solution is:
//   - FK of the solution reproduces the target within epsilon (tolerance bounds applied)
//   - every joint value lies inside its limits
//   - the solve rate over a sample of reachable targets clears a generous floor
// Target poses are generated by forward kinematics from a random full configuration, so every target
// is reachable by construction; the expected value comes from KDL's FK solver, not from the IK code.
//
// Four fixtures, shared with the plugin seam and found through the TRAC_IK_TEST_FIXTURE_DIR compile
// definition: the mesh-stripped crane (9 joints, 4 mimic, 5 active), arm6 (a plain 6-DOF arm),
// arm7 (redundant 7R) and mimic_arm (one revolute mimic, negative multiplier, nonzero offset).

#include <gtest/gtest.h>

#include <kdl/chainfksolverpos_recursive.hpp>
#include <kdl_parser/kdl_parser.hpp>
#include <trac_ik/trac_ik.hpp>
// Jazzy's urdf 2.10.1 has no <urdf/model.hpp>; on Kilted and Rolling <urdf/model.h> is a shim that
// warns. Delete this guard, keeping the .hpp, when Jazzy reaches EOL (May 2029).
#if __has_include(<urdf/model.hpp>)
#include <urdf/model.hpp>
#else
#include <urdf/model.h>
#endif

#include <cstdlib>
#include <fstream>
#include <limits>
#include <random>
#include <sstream>
#include <string>
#include <vector>

namespace
{

constexpr double kEps = 1e-5;       // solver convergence threshold
constexpr double kPosTol = 1e-3;    // metres, FK round-trip
constexpr double kRotTol = 1e-3;    // radians, FK round-trip
constexpr int kSamples = 200;
constexpr double kSolveRateFloor = 0.90;  // generous: tighten once ticket 10 seeds the RNG

// The per-solve budget, in seconds. Defaults to MoveIt's own kinematics_solver_timeout, which is
// what a user's robot gets; CI sets TRAC_IK_TEST_SOLVE_BUDGET to a looser value, because a shared
// runner is slower and noisier than the machine these bounds were chosen on and should fail on
// behaviour, not on wall-clock. No test asserts a duration, so raising it can only help a solve --
// up to the target's own ctest timeout, which is why the value is range-checked.
double solveBudget()
{
  static const double budget = []() {
    constexpr double kDefault = 0.05;
    const char* env = std::getenv("TRAC_IK_TEST_SOLVE_BUDGET");
    if (!env)
      return kDefault;
    // strtod, not atof: atof accepts trailing garbage, so "200ms" would parse as a 200-second
    // budget, quietly blow through the target's own 300 s ctest timeout and kill the cell with no
    // hint that the variable is at fault. A mistyped budget must fail as a misconfiguration.
    char* end = nullptr;
    const double parsed = std::strtod(env, &end);
    // Upper bound because the budget multiplies out: the plugin's sampled tests spend it on all 50
    // samples, so 1 s is already 150 s of the target's 300 s ctest TIMEOUT. Past that the cell dies
    // on wall-clock, which is the failure mode this variable exists to prevent.
    const bool ok = end && *end == '\0' && end != env && parsed > 0.0 && parsed <= 1.0;
    EXPECT_TRUE(ok) << "TRAC_IK_TEST_SOLVE_BUDGET must be a bare number of seconds in (0, 1]: " << env;
    return ok ? parsed : kDefault;
  }();
  return budget;
}

// This suite's query: the budget and epsilon every test solves with. Timeout, epsilon, solve type
// and the tolerance bounds live on the query rather than on the solver, so one instance answers
// every sample in a test.
TRAC_IK::Query defaultQuery(TRAC_IK::SolveType type = TRAC_IK::Speed)
{
  TRAC_IK::Query q;
  q.timeout = solveBudget();
  q.epsilon = kEps;
  q.solve_type = type;
  return q;
}

std::string readFixture(const std::string& name)
{
  std::ifstream in(std::string(TRAC_IK_TEST_FIXTURE_DIR) + "/" + name);
  EXPECT_TRUE(in.good()) << "fixture not found: " << name;
  std::stringstream ss;
  ss << in.rdbuf();
  return ss.str();
}

// The chain, its limits, and an FK solver: everything a library-seam test needs.
struct Fixture
{
  urdf::Model model;
  KDL::Chain chain;
  KDL::JntArray lb, ub;
  std::vector<std::string> joint_names;
  /// The couplings the URDF declares, ready to hand to a solver. A solve test that wants the
  /// mechanism the fixture actually describes passes this; one that wants the chain treated as
  /// uncoupled passes nothing, which is how the arm fixtures stay a regression on the default.
  TRAC_IK::JointCouplings couplings;

  Fixture(const std::string& urdf_file, const std::string& base, const std::string& tip)
  {
    const std::string xml = readFixture(urdf_file);
    EXPECT_TRUE(model.initString(xml));
    KDL::Tree tree;
    EXPECT_TRUE(kdl_parser::treeFromString(xml, tree));
    EXPECT_TRUE(tree.getChain(base, tip, chain));

    lb.resize(chain.getNrOfJoints());
    ub.resize(chain.getNrOfJoints());
    unsigned int i = 0;
    for (const auto& seg : chain.segments)
    {
      auto joint = model.getJoint(seg.getJoint().getName());
      if (!joint || joint->type == urdf::Joint::UNKNOWN || joint->type == urdf::Joint::FIXED)
        continue;
      joint_names.push_back(joint->name);
      // Mirrors trac_ik.cpp: a continuous joint is reported as unbounded via float sentinels.
      if (joint->type == urdf::Joint::CONTINUOUS)
      {
        lb(i) = std::numeric_limits<float>::lowest();
        ub(i) = std::numeric_limits<float>::max();
      }
      else
      {
        lb(i) = joint->limits->lower;
        ub(i) = joint->limits->upper;
      }
      ++i;
    }
    EXPECT_EQ(i, chain.getNrOfJoints());

    couplings = TRAC_IK::JointCouplings(couplingDescription());
    EXPECT_TRUE(couplings.valid()) << couplings.error();
  }

  // The description a caller hands the library, read off the same URDF this fixture parsed. This is
  // what the plugin will build from MoveIt's robot model in ticket 06.
  std::vector<TRAC_IK::JointCoupling> couplingDescription() const
  {
    std::vector<TRAC_IK::JointCoupling> out(chain.getNrOfJoints());
    for (unsigned int i = 0; i < joint_names.size(); ++i)
    {
      out[i].name = joint_names[i];
      const auto joint = model.getJoint(joint_names[i]);
      if (!joint->mimic)
        continue;
      out[i].mimicked_index = indexOf(joint->mimic->joint_name);
      out[i].multiplier = joint->mimic->multiplier;
      out[i].offset = joint->mimic->offset;
    }
    return out;
  }

  bool unbounded(unsigned int i) const
  {
    return ub(i) >= std::numeric_limits<float>::max() && lb(i) <= std::numeric_limits<float>::lowest();
  }

  KDL::Frame fk(const KDL::JntArray& q) const
  {
    KDL::ChainFkSolverPos_recursive solver(chain);
    KDL::Frame f;
    EXPECT_GE(solver.JntToCart(q, f), 0);
    return f;
  }

  // A random full configuration inside the limits; continuous joints sample [-pi, pi].
  KDL::JntArray randomConfig(std::mt19937& rng) const
  {
    KDL::JntArray q(chain.getNrOfJoints());
    for (unsigned int i = 0; i < chain.getNrOfJoints(); ++i)
    {
      const double lo = unbounded(i) ? -M_PI : lb(i);
      const double hi = unbounded(i) ? M_PI : ub(i);
      q(i) = std::uniform_real_distribution<double>(lo, hi)(rng);
    }
    return q;
  }

  int indexOf(const std::string& joint_name) const
  {
    for (unsigned int i = 0; i < joint_names.size(); ++i)
      if (joint_names[i] == joint_name)
        return static_cast<int>(i);
    return -1;
  }

  // A random full configuration that satisfies every coupling the URDF declares, so a target built
  // from it is reachable whether or not the solver knows about mimic joints. The sampling interval
  // of a mimicked joint is tightened by the interval its mimic's own limits map back to -- those can
  // be narrower than the multiplier would induce, and mimic_arm's deliberately are. The mapping is
  // sign-aware: a negative multiplier swaps the ends.
  KDL::JntArray mimicConsistentConfig(std::mt19937& rng) const
  {
    std::vector<double> lo(chain.getNrOfJoints()), hi(chain.getNrOfJoints());
    for (unsigned int i = 0; i < chain.getNrOfJoints(); ++i)
    {
      lo[i] = unbounded(i) ? -M_PI : lb(i);
      hi[i] = unbounded(i) ? M_PI : ub(i);
    }
    for (unsigned int i = 0; i < joint_names.size(); ++i)
    {
      const auto joint = model.getJoint(joint_names[i]);
      if (!joint->mimic || joint->mimic->multiplier == 0.0)
        continue;
      // Same rule as expectMimicCouplings: a mimic whose target is outside the chain is a fixture
      // this helper cannot sample, not something to skip quietly -- skipping it would build a
      // coupling-violating target that the assertion then reports as a solver bug.
      const int j = indexOf(joint->mimic->joint_name);
      if (j < 0)
      {
        ADD_FAILURE() << joint_names[i] << " mimics a joint outside the chain";
        return KDL::JntArray(chain.getNrOfJoints());
      }
      double a = (lo[i] - joint->mimic->offset) / joint->mimic->multiplier;
      double b = (hi[i] - joint->mimic->offset) / joint->mimic->multiplier;
      if (a > b)  // sign-aware: a negative multiplier swaps the ends
        std::swap(a, b);
      lo[j] = std::max(lo[j], a);
      hi[j] = std::min(hi[j], b);
      // An empty intersection would hand uniform_real_distribution an inverted range, which is
      // undefined behaviour and would surface as a silently garbage target rather than a diagnosis.
      if (lo[j] > hi[j])
      {
        ADD_FAILURE() << joint_names[i] << " and " << joint->mimic->joint_name
                      << " have no jointly satisfiable interval";
        return KDL::JntArray(chain.getNrOfJoints());
      }
    }

    KDL::JntArray q(chain.getNrOfJoints());
    for (unsigned int i = 0; i < joint_names.size(); ++i)
      if (!model.getJoint(joint_names[i])->mimic)
        q(i) = std::uniform_real_distribution<double>(lo[i], hi[i])(rng);
    for (unsigned int i = 0; i < joint_names.size(); ++i)
    {
      const auto joint = model.getJoint(joint_names[i]);
      if (!joint->mimic)
        continue;
      q(i) = joint->mimic->multiplier * q(indexOf(joint->mimic->joint_name)) + joint->mimic->offset;
    }
    return q;
  }
};

void expectWithinLimits(const Fixture& f, const KDL::JntArray& q)
{
  for (unsigned int i = 0; i < q.rows(); ++i)
  {
    if (f.unbounded(i))
      continue;
    EXPECT_GE(q(i), f.lb(i) - 1e-6) << "joint " << f.joint_names[i] << " below its lower limit";
    EXPECT_LE(q(i), f.ub(i) + 1e-6) << "joint " << f.joint_names[i] << " above its upper limit";
  }
}

double positionError(const KDL::Frame& a, const KDL::Frame& b)
{
  return (a.p - b.p).Norm();
}

double rotationError(const KDL::Frame& a, const KDL::Frame& b)
{
  return (a.M.Inverse() * b.M).GetRot().Norm();
}

// Every mimic joint holds multiplier * mimicked + offset. What "the solver respects the coupling"
// means, and the assertion tickets 04 and 05 turn green.
void expectMimicCouplings(const Fixture& f, const KDL::JntArray& q)
{
  for (unsigned int i = 0; i < f.joint_names.size(); ++i)
  {
    const auto joint = f.model.getJoint(f.joint_names[i]);
    if (!joint->mimic)
      continue;
    const int j = f.indexOf(joint->mimic->joint_name);
    ASSERT_GE(j, 0) << f.joint_names[i] << " mimics a joint outside the chain";
    EXPECT_NEAR(q(i), joint->mimic->multiplier * q(j) + joint->mimic->offset, 1e-6)
        << f.joint_names[i] << " must follow " << joint->mimic->joint_name;
  }
}

}  // namespace

// ---------------------------------------------------------------------------------------------
// arm6: a conventional 6-DOF arm, no mimic joints. Keeps the suite honest about the regressions
// the crane (5 active DOF, position-only) cannot show.
// ---------------------------------------------------------------------------------------------

TEST(TracIkLib, Arm6FullPoseRoundTrip)
{
  Fixture f("arm6.urdf", "base_link", "tool_link");
  TRAC_IK::TRAC_IK ik(f.chain, f.lb, f.ub);
  TRAC_IK::Query q = defaultQuery();

  std::mt19937 rng(1);  // test-side determinism: the TARGETS repeat, the solver's search does not
  int solved = 0;
  for (int n = 0; n < kSamples; ++n)
  {
    const KDL::Frame target = f.fk(f.randomConfig(rng));
    KDL::JntArray seed = f.randomConfig(rng), sol;
    if (ik.CartToJnt(seed, target, sol, q) < 0)
      continue;
    ++solved;
    expectWithinLimits(f, sol);
    const KDL::Frame reached = f.fk(sol);
    EXPECT_LT(positionError(target, reached), kPosTol);
    EXPECT_LT(rotationError(target, reached), kRotTol);
  }
  EXPECT_GE(static_cast<double>(solved) / kSamples, kSolveRateFloor)
      << "solved " << solved << " of " << kSamples;
}

TEST(TracIkLib, Arm6PositionOnlyToleranceFreesOrientation)
{
  Fixture f("arm6.urdf", "base_link", "tool_link");
  TRAC_IK::TRAC_IK ik(f.chain, f.lb, f.ub);
  TRAC_IK::Query q = defaultQuery();

  // Infinite rotational tolerance bounds: the three orientation components are free.
  q.tolerance_bounds.rot.x(std::numeric_limits<float>::max());
  q.tolerance_bounds.rot.y(std::numeric_limits<float>::max());
  q.tolerance_bounds.rot.z(std::numeric_limits<float>::max());

  std::mt19937 rng(2);
  int solved = 0;
  for (int n = 0; n < kSamples; ++n)
  {
    const KDL::Frame target = f.fk(f.randomConfig(rng));
    KDL::JntArray seed = f.randomConfig(rng), sol;
    if (ik.CartToJnt(seed, target, sol, q) < 0)
      continue;
    ++solved;
    expectWithinLimits(f, sol);
    // Position must still be met; orientation is explicitly not asserted.
    EXPECT_LT(positionError(target, f.fk(sol)), kPosTol);
  }
  EXPECT_GE(static_cast<double>(solved) / kSamples, kSolveRateFloor)
      << "solved " << solved << " of " << kSamples;
}

TEST(TracIkLib, Arm6ContinuousJointsAreUnbounded)
{
  Fixture f("arm6.urdf", "base_link", "tool_link");
  KDL::JntArray lb, ub;
  TRAC_IK::TRAC_IK ik(f.chain, f.lb, f.ub);
  ASSERT_TRUE(ik.getKDLLimits(lb, ub));
  for (unsigned int i = 0; i < f.joint_names.size(); ++i)
  {
    const bool is_continuous = f.model.getJoint(f.joint_names[i])->type == urdf::Joint::CONTINUOUS;
    EXPECT_EQ(is_continuous, f.unbounded(i)) << "joint " << f.joint_names[i];
  }
}

// ---------------------------------------------------------------------------------------------
// The crane: 9 chain joints, 4 of them mimic joints, 5 active. Told how its chain is coupled, the
// solver chooses 5 values and computes the other 4, so a solution satisfies the couplings exactly
// rather than approximately -- which is what the tests below assert, on one sample and on a set.
// ---------------------------------------------------------------------------------------------

TEST(TracIkLib, CraneChainShape)
{
  Fixture f("crane.urdf", "base_link", "jib_ext_link");
  EXPECT_EQ(f.chain.getNrOfJoints(), 9u) << "the crane chain has 9 joints with variables";
  int mimics = 0;
  for (const auto& name : f.joint_names)
    if (f.model.getJoint(name)->mimic)
      ++mimics;
  EXPECT_EQ(mimics, 4) << "4 of them are mimic joints";
}

// A query with the three orientation axes freed. Both coupled fixtures are asked for position with
// orientation free, because enforcing their couplings is exactly what takes away the degrees of
// freedom an arbitrary 6-axis pose would need: the crane is left with 5 and mimic_arm with 3. It is
// also what the crane is asked for in service, and what ticket 09 makes its shipped default.
TRAC_IK::Query positionOnlyQuery(TRAC_IK::SolveType type)
{
  TRAC_IK::Query q = defaultQuery(type);
  q.tolerance_bounds.rot.x(std::numeric_limits<float>::max());
  q.tolerance_bounds.rot.y(std::numeric_limits<float>::max());
  q.tolerance_bounds.rot.z(std::numeric_limits<float>::max());
  return q;
}

TEST(TracIkLib, CraneSolutionRespectsMimicCoupling)
{
  Fixture f("crane.urdf", "base_link", "jib_ext_link");
  // TRAP, pinned deliberately: Distance, not Speed. In Speed mode the KDL branch answers in ~1 ms
  // with a solution whose four parallel prismatic joints happen to be equal -- their Jacobian
  // columns are identical and repeated limit clipping collapses them together -- so the coupling
  // looks intact and this test goes green for a reason that has nothing to do with mimic support.
  // Distance collects solutions for the whole budget and its winner violates the coupling outright
  // (up to 0.86 on main_boom_ext_4, measured). Crane coupling tests therefore pin Distance rather
  // than leaning on the shipped default, and no mimic work may accept a green Speed-mode run as
  // evidence.
  TRAC_IK::TRAC_IK ik(f.chain, f.lb, f.ub, f.couplings);
  TRAC_IK::Query q = positionOnlyQuery(TRAC_IK::Distance);

  // A mimic-consistent full configuration, so the target is reachable under the coupling.
  std::mt19937 rng(3);
  const KDL::Frame target = f.fk(f.mimicConsistentConfig(rng));

  // TRAP, pinned deliberately: NOT a zero seed. The four main_boom_ext* joints are parallel
  // prismatic joints with identical Jacobian columns, so from an all-equal seed a pseudo-inverse
  // step moves them by equal amounts and the mimic violation stays invisible, exactly as in Speed
  // mode. An asymmetric seed is what exposes it.
  KDL::JntArray seed = f.randomConfig(rng), sol;
  ASSERT_GE(ik.CartToJnt(seed, target, sol, q), 0) << "no solution for a reachable crane pose";
  EXPECT_LT(positionError(target, f.fk(sol)), kPosTol) << "the 5 active joints do reach the target";
  expectWithinLimits(f, sol);
  expectMimicCouplings(f, sol);
}

// Not one sample: the coupling has to hold on every solution, not on a lucky one, and the two
// branches race, so which of them answers varies from sample to sample.
TEST(TracIkLib, CraneSolutionsRespectMimicCouplingOverASampleSet)
{
  Fixture f("crane.urdf", "base_link", "jib_ext_link");
  TRAC_IK::TRAC_IK ik(f.chain, f.lb, f.ub, f.couplings);
  TRAC_IK::Query q = positionOnlyQuery(TRAC_IK::Distance);

  std::mt19937 rng(31);
  int solved = 0;
  for (int n = 0; n < 40; ++n)
  {
    const KDL::Frame target = f.fk(f.mimicConsistentConfig(rng));
    KDL::JntArray seed = f.randomConfig(rng), sol;
    if (ik.CartToJnt(seed, target, sol, q) < 0)
      continue;
    ++solved;
    EXPECT_LT(positionError(target, f.fk(sol)), kPosTol);
    expectWithinLimits(f, sol);
    expectMimicCouplings(f, sol);
  }
  EXPECT_GE(static_cast<double>(solved) / 40, kSolveRateFloor) << "solved " << solved << " of 40";
}

// A seed is a full configuration and a caller may hand one that the mechanism cannot hold: mimic
// entries that do not follow their mimicked joints, and a mimicked joint outside the bounds the
// couplings leave it. Neither is an error -- the solver recomputes the mimic entries and clamps the
// rest -- and neither may reach the solution.
TEST(TracIkLib, ASeedOffItsCouplingIsRepairedRatherThanRefused)
{
  Fixture f("crane.urdf", "base_link", "jib_ext_link");
  TRAC_IK::TRAC_IK ik(f.chain, f.lb, f.ub, f.couplings);
  TRAC_IK::Query q = positionOnlyQuery(TRAC_IK::Distance);

  std::mt19937 rng(32);
  const KDL::Frame target = f.fk(f.mimicConsistentConfig(rng));

  KDL::JntArray seed = f.mimicConsistentConfig(rng), sol;
  // Off its coupling by a lot, and one mimicked joint driven past its own upper limit.
  for (unsigned int i = 0; i < f.joint_names.size(); ++i)
    if (f.model.getJoint(f.joint_names[i])->mimic)
      seed(i) = f.lb(i);
  const int mimicked = f.indexOf("main_boom_ext");
  ASSERT_GE(mimicked, 0);
  seed(mimicked) = f.ub(mimicked) + 5.0;

  ASSERT_GE(ik.CartToJnt(seed, target, sol, q), 0) << "a repairable seed is not a reason to fail";
  EXPECT_LT(positionError(target, f.fk(sol)), kPosTol);
  expectWithinLimits(f, sol);
  expectMimicCouplings(f, sol);
}

// The same, on the fixture whose tightening actually bites: mimic_arm's j2 has a narrower effective
// range than its own limits, so a seed inside its URDF limits can still be outside what the
// mechanism can hold. The clamp is to the EFFECTIVE bounds, which is the only clamp that leaves the
// mimic joint inside its own limits too.
TEST(TracIkLib, ASeedInsideItsOwnLimitsButOutsideTheEffectiveOnesIsClamped)
{
  Fixture f("mimic_arm.urdf", "base_link", "tool_link");
  TRAC_IK::TRAC_IK ik(f.chain, f.lb, f.ub, f.couplings);
  KDL::JntArray lb, ub;
  ASSERT_TRUE(ik.getKDLLimits(lb, ub));

  const int j2 = f.indexOf("j2");
  ASSERT_GE(j2, 0);
  ASSERT_LT(ub(j2), f.ub(j2)) << "j2's effective upper bound must be the tighter one";

  TRAC_IK::Query q = positionOnlyQuery(TRAC_IK::Distance);

  std::mt19937 rng(33);
  const KDL::Frame target = f.fk(f.mimicConsistentConfig(rng));

  KDL::JntArray seed = f.mimicConsistentConfig(rng), sol;
  seed(j2) = (ub(j2) + f.ub(j2)) / 2.0;  // inside the URDF's limits, outside the effective ones

  ASSERT_GE(ik.CartToJnt(seed, target, sol, q), 0);
  EXPECT_LT(positionError(target, f.fk(sol)), kPosTol);
  expectWithinLimits(f, sol);
  expectMimicCouplings(f, sol);
  for (unsigned int i = 0; i < f.chain.getNrOfJoints(); ++i)
  {
    EXPECT_GE(sol(i), lb(i) - 1e-6) << f.joint_names[i] << " below its effective lower bound";
    EXPECT_LE(sol(i), ub(i) + 1e-6) << f.joint_names[i] << " above its effective upper bound";
  }
}

TEST(TracIkLib, MimicArmSolutionRespectsMimicCoupling)
{
  Fixture f("mimic_arm.urdf", "base_link", "tool_link");
  TRAC_IK::TRAC_IK ik(f.chain, f.lb, f.ub, f.couplings);
  TRAC_IK::Query q = positionOnlyQuery(TRAC_IK::Distance);

  std::mt19937 rng(34);
  int solved = 0;
  for (int n = 0; n < 40; ++n)
  {
    const KDL::Frame target = f.fk(f.mimicConsistentConfig(rng));
    KDL::JntArray seed = f.randomConfig(rng), sol;
    if (ik.CartToJnt(seed, target, sol, q) < 0)
      continue;
    ++solved;
    EXPECT_LT(positionError(target, f.fk(sol)), kPosTol);
    expectWithinLimits(f, sol);
    // A negative multiplier and a nonzero offset: the crane cannot catch a sign error here.
    expectMimicCouplings(f, sol);
  }
  EXPECT_GE(static_cast<double>(solved) / 40, kSolveRateFloor) << "solved " << solved << " of 40";
}

// Distance ranks by joint distance from the seed, and joint distance is measured over the joints the
// solver chose. Counting a mimic entry too would weight the crane's four-stage telescope x4 against
// its one-stage jib, so the winner would not be the closest configuration in any sense a caller
// means.
TEST(TracIkLib, DistanceRanksTheReducedConfiguration)
{
  Fixture f("crane.urdf", "base_link", "jib_ext_link");
  TRAC_IK::TRAC_IK ik(f.chain, f.lb, f.ub, f.couplings);
  TRAC_IK::Query q = positionOnlyQuery(TRAC_IK::Distance);

  const auto reducedSqDistance = [&f](const KDL::JntArray& a, const KDL::JntArray& b) {
    double sum = 0;
    for (const unsigned int i : f.couplings.activeIndices())
      sum += (a(i) - b(i)) * (a(i) - b(i));
    return sum;
  };

  std::mt19937 rng(35);
  const KDL::Frame target = f.fk(f.mimicConsistentConfig(rng));
  // A seed that already satisfies the couplings, so the key is measured from what the caller passed.
  KDL::JntArray seed = f.mimicConsistentConfig(rng), sol;
  ASSERT_GE(ik.CartToJnt(seed, target, sol, q), 0);

  std::vector<KDL::JntArray> candidates;
  std::vector<std::pair<double, uint> > keys;
  ASSERT_TRUE(ik.getSolutions(candidates, keys));
  ASSERT_FALSE(keys.empty());

  // The ordering key IS the reduced squared distance -- on a coupled chain the full sum is a
  // different number, so this equality is what tells the two apart.
  for (const auto& key : keys)
    EXPECT_NEAR(key.first, reducedSqDistance(seed, candidates[key.second]), 1e-9);

  // ...and the returned solution is the closest of them under that measure.
  for (const auto& candidate : candidates)
    EXPECT_LE(reducedSqDistance(seed, sol), reducedSqDistance(seed, candidate) + 1e-9);
}

// ---------------------------------------------------------------------------------------------
// The query (ticket 03). Timeout, epsilon, solve type, tolerance bounds and the per-call joint
// bounds are a parameter of CartToJnt, not solver state, so one instance answers many questions.
// ---------------------------------------------------------------------------------------------

// A query whose joint bounds are strictly inside the mechanism's: the middle half of every bounded
// joint's range, and [-1, 1] rad for the continuous ones, which have no range to halve. Continuous
// joints are narrowed on purpose -- a rotational joint is continuous for a call exactly when the
// bounds in force are infinite, so a finite pair here must bound it like any other joint.
TRAC_IK::Query narrowedQuery(const Fixture& f, TRAC_IK::SolveType type = TRAC_IK::Speed)
{
  TRAC_IK::Query q = defaultQuery(type);
  q.q_min.resize(f.chain.getNrOfJoints());
  q.q_max.resize(f.chain.getNrOfJoints());
  for (unsigned int i = 0; i < f.chain.getNrOfJoints(); ++i)
  {
    const double quarter = f.unbounded(i) ? 0.0 : (f.ub(i) - f.lb(i)) / 4.0;
    q.q_min(i) = f.unbounded(i) ? -1.0 : f.lb(i) + quarter;
    q.q_max(i) = f.unbounded(i) ? 1.0 : f.ub(i) - quarter;
  }
  return q;
}

TEST(TracIkLib, QueryJointBoundsNarrowTheSearchWithoutChangingTheMechanism)
{
  Fixture f("arm6.urdf", "base_link", "tool_link");
  TRAC_IK::TRAC_IK ik(f.chain, f.lb, f.ub);
  const TRAC_IK::Query q = narrowedQuery(f);

  // Targets are taken from configurations inside the narrowed box, so they stay reachable under it.
  std::mt19937 rng(21);
  int solved = 0;
  for (int n = 0; n < 40; ++n)
  {
    KDL::JntArray inside(f.chain.getNrOfJoints());
    for (unsigned int i = 0; i < f.chain.getNrOfJoints(); ++i)
      inside(i) = std::uniform_real_distribution<double>(q.q_min(i), q.q_max(i))(rng);
    const KDL::Frame target = f.fk(inside);
    // Seeded from OUTSIDE the box on purpose: a seed inside it would leave the first Newton step
    // inside whether or not the query's bounds were honoured, and the test would pass for nothing.
    KDL::JntArray seed = f.randomConfig(rng), sol;
    if (ik.CartToJnt(seed, target, sol, q) < 0)
      continue;
    ++solved;
    for (unsigned int i = 0; i < f.chain.getNrOfJoints(); ++i)
    {
      EXPECT_GE(sol(i), q.q_min(i) - kEps) << "joint " << f.joint_names[i] << " below the query's bound";
      EXPECT_LE(sol(i), q.q_max(i) + kEps) << "joint " << f.joint_names[i] << " above the query's bound";
    }
  }
  EXPECT_GT(solved, 0) << "the narrowed box must still admit solutions";

  // The mechanism is untouched: getKDLLimits still answers with what the constructor was given.
  KDL::JntArray lb, ub;
  ASSERT_TRUE(ik.getKDLLimits(lb, ub));
  for (unsigned int i = 0; i < f.chain.getNrOfJoints(); ++i)
  {
    EXPECT_DOUBLE_EQ(lb(i), f.lb(i));
    EXPECT_DOUBLE_EQ(ub(i), f.ub(i));
  }
}

TEST(TracIkLib, OneInstanceAnswersQueriesThatDisagree)
{
  Fixture f("arm6.urdf", "base_link", "tool_link");
  TRAC_IK::TRAC_IK ik(f.chain, f.lb, f.ub);

  std::mt19937 rng(22);
  const KDL::JntArray goal = f.randomConfig(rng);
  const KDL::Frame target = f.fk(goal);
  KDL::JntArray seed = f.randomConfig(rng);

  // Three queries in a row on one instance, each changing something the constructor used to own:
  // the solve type, the joint bounds (which rebuild the inner solvers and reclassify the continuous
  // joints), and then back again. Every one must be answered on its own terms -- nothing may
  // survive from the query before it.
  for (const TRAC_IK::Query& q : { defaultQuery(), narrowedQuery(f, TRAC_IK::Distance), defaultQuery(TRAC_IK::Distance) })
  {
    KDL::JntArray sol;
    if (ik.CartToJnt(seed, target, sol, q) < 0)
      continue;  // a single sample may legitimately fail; a wrong answer may not
    EXPECT_LT(positionError(target, f.fk(sol)), kPosTol);
    EXPECT_LT(rotationError(target, f.fk(sol)), kRotTol);
    expectWithinLimits(f, sol);
  }
}

// ---------------------------------------------------------------------------------------------
// arm7 (wayfinder ticket 22): a redundant 7R arm. Against a full-pose goal its 6x7 Jacobian has a
// one-dimensional null space, a third regime the suite lacked -- the crane is rank-deficient and
// arm6 is square. Redundancy is what TRAC-IK's own audience has.
// ---------------------------------------------------------------------------------------------

TEST(TracIkLib, Arm7FullPoseRoundTrip)
{
  Fixture f("arm7.urdf", "base_link", "tool_link");
  ASSERT_EQ(f.chain.getNrOfJoints(), 7u);
  TRAC_IK::TRAC_IK ik(f.chain, f.lb, f.ub);
  TRAC_IK::Query q = defaultQuery();

  std::mt19937 rng(7);
  int solved = 0;
  for (int n = 0; n < kSamples; ++n)
  {
    const KDL::Frame target = f.fk(f.randomConfig(rng));
    KDL::JntArray seed = f.randomConfig(rng), sol;
    if (ik.CartToJnt(seed, target, sol, q) < 0)
      continue;
    ++solved;
    expectWithinLimits(f, sol);
    const KDL::Frame reached = f.fk(sol);
    EXPECT_LT(positionError(target, reached), kPosTol);
    EXPECT_LT(rotationError(target, reached), kRotTol);
  }
  EXPECT_GE(static_cast<double>(solved) / kSamples, kSolveRateFloor)
      << "solved " << solved << " of " << kSamples;
}

TEST(TracIkLib, Arm7PositionOnlyToleranceFreesOrientation)
{
  Fixture f("arm7.urdf", "base_link", "tool_link");
  TRAC_IK::TRAC_IK ik(f.chain, f.lb, f.ub);
  TRAC_IK::Query q = defaultQuery();

  q.tolerance_bounds.rot.x(std::numeric_limits<float>::max());
  q.tolerance_bounds.rot.y(std::numeric_limits<float>::max());
  q.tolerance_bounds.rot.z(std::numeric_limits<float>::max());

  std::mt19937 rng(8);
  int solved = 0;
  for (int n = 0; n < kSamples; ++n)
  {
    const KDL::Frame target = f.fk(f.randomConfig(rng));
    KDL::JntArray seed = f.randomConfig(rng), sol;
    if (ik.CartToJnt(seed, target, sol, q) < 0)
      continue;
    ++solved;
    expectWithinLimits(f, sol);
    EXPECT_LT(positionError(target, f.fk(sol)), kPosTol);
  }
  EXPECT_GE(static_cast<double>(solved) / kSamples, kSolveRateFloor)
      << "solved " << solved << " of " << kSamples;
}

// The self-motion witness: one target, many seeds, genuinely different configurations that all
// reach it. This is the property ticket 07's "walk the candidate list against the validity
// callback" leans on and neither existing fixture has (the crane's spare DOF is a coupling, and
// arm6's square Jacobian gives isolated solutions only).
TEST(TracIkLib, Arm7HasANullSpaceOfSolutions)
{
  Fixture f("arm7.urdf", "base_link", "tool_link");
  TRAC_IK::TRAC_IK ik(f.chain, f.lb, f.ub);
  TRAC_IK::Query q = defaultQuery();

  std::mt19937 rng(9);
  const KDL::Frame target = f.fk(f.randomConfig(rng));

  std::vector<KDL::JntArray> found;
  for (int n = 0; n < 20; ++n)
  {
    KDL::JntArray seed = f.randomConfig(rng), sol;
    if (ik.CartToJnt(seed, target, sol, q) < 0)
      continue;
    ASSERT_LT(positionError(target, f.fk(sol)), kPosTol);
    ASSERT_LT(rotationError(target, f.fk(sol)), kRotTol);
    found.push_back(sol);
  }
  ASSERT_GE(found.size(), 5u) << "the redundant arm should reach one pose from most seeds";

  double widest = 0.0;
  for (size_t a = 0; a < found.size(); ++a)
    for (size_t b = a + 1; b < found.size(); ++b)
    {
      double d = 0.0;
      for (unsigned int i = 0; i < found[a].rows(); ++i)
        d = std::max(d, std::fabs(found[a](i) - found[b](i)));
      widest = std::max(widest, d);
    }
  EXPECT_GT(widest, 0.1) << "distinct solutions for one pose; widest joint spread " << widest;
}

// ---------------------------------------------------------------------------------------------
// mimic_arm (wayfinder ticket 05): the commonest mimic robot on earth -- one revolute mimic at a
// negative multiplier and a nonzero offset, whose own limits are tighter than its mimicked joint's
// map onto. The crane covers "prismatic, x1, +0" and nothing else, so a sign error in the bound
// mapping or in the folded Jacobian is invisible without this fixture.
// ---------------------------------------------------------------------------------------------

TEST(TracIkLib, MimicArmChainShape)
{
  Fixture f("mimic_arm.urdf", "base_link", "tool_link");
  ASSERT_EQ(f.chain.getNrOfJoints(), 4u) << "4 chain joints with variables, 3 of them active";

  const int mimic = f.indexOf("j3");
  const int mimicked = f.indexOf("j2");
  ASSERT_GE(mimic, 0);
  ASSERT_GE(mimicked, 0);
  const auto coupling = f.model.getJoint("j3")->mimic;
  ASSERT_TRUE(static_cast<bool>(coupling));
  EXPECT_EQ(coupling->joint_name, "j2");
  EXPECT_DOUBLE_EQ(coupling->multiplier, -0.5) << "negative on purpose: the crane's are all +1";
  EXPECT_DOUBLE_EQ(coupling->offset, 0.3) << "nonzero on purpose: the crane's are all 0";
  EXPECT_GT(mimic, mimicked) << "the mimic joint sits downstream of the joint it follows";

  // The tightening this fixture exists to make bite: j2's declared limits map onto an interval
  // wider than j3's own, so j2's effective range is strictly narrower than what the URDF declares.
  const double mapped_lo = (f.ub(mimic) - coupling->offset) / coupling->multiplier;  // multiplier < 0
  const double mapped_hi = (f.lb(mimic) - coupling->offset) / coupling->multiplier;  // so ends swap
  EXPECT_GT(mapped_lo, f.lb(mimicked)) << "j3's lower limit must tighten j2 from below";
  EXPECT_LT(mapped_hi, f.ub(mimicked)) << "j3's upper limit must tighten j2 from above";
}

TEST(TracIkLib, MimicArmPositionOnlyRoundTrip)
{
  Fixture f("mimic_arm.urdf", "base_link", "tool_link");
  TRAC_IK::TRAC_IK ik(f.chain, f.lb, f.ub, f.couplings);
  TRAC_IK::Query q = defaultQuery();

  // Three active joints against a three-dimensional position goal: orientation is left free, so the
  // query stays solvable once the coupling is enforced and the solver has 3 variables, not 4.
  q.tolerance_bounds.rot.x(std::numeric_limits<float>::max());
  q.tolerance_bounds.rot.y(std::numeric_limits<float>::max());
  q.tolerance_bounds.rot.z(std::numeric_limits<float>::max());

  std::mt19937 rng(11);
  int solved = 0;
  for (int n = 0; n < kSamples; ++n)
  {
    const KDL::Frame target = f.fk(f.mimicConsistentConfig(rng));
    KDL::JntArray seed = f.randomConfig(rng), sol;
    if (ik.CartToJnt(seed, target, sol, q) < 0)
      continue;
    ++solved;
    expectWithinLimits(f, sol);
    EXPECT_LT(positionError(target, f.fk(sol)), kPosTol);
  }
  EXPECT_GE(static_cast<double>(solved) / kSamples, kSolveRateFloor)
      << "solved " << solved << " of " << kSamples;
}

// ---------------------------------------------------------------------------------------------
// Joint couplings and effective bounds (ticket 04). The value type owns expand, reduce, tighten and
// the reduced Jacobian; the solver is told how its chain is coupled at construction and answers
// honestly about what range each joint can actually take. These are tests of the value and of the
// bounds it produces; that a SOLUTION satisfies a coupling is asserted with the solves above.
// ---------------------------------------------------------------------------------------------

namespace
{

// The fixture's own description, under the name the tests below already use. Spelling it out is
// what lets each refusal test corrupt one field of a description that is otherwise well-formed.
std::vector<TRAC_IK::JointCoupling> couplingsOf(const Fixture& f)
{
  return f.couplingDescription();
}

// The two coupled fixtures, each named by one mimic joint and the joint it follows. The refusals
// below are properties of the description rather than of a robot, so each is checked on both: the
// crane (prismatic, multiplier 1, offset 0) and mimic_arm (revolute, negative multiplier, offset).
struct CoupledFixture
{
  const char* urdf;
  const char* tip;
  const char* mimic;
  const char* mimicked;
};

const CoupledFixture kCoupledFixtures[] = {
  { "crane.urdf", "jib_ext_link", "jib_ext_2", "jib_ext" },
  { "mimic_arm.urdf", "tool_link", "j3", "j2" },
};

// A description the JointCouplings constructor must refuse, checked at both seams it can be refused
// at: the value itself, and the solver that was handed it. A solver that took the description anyway
// would answer queries about a mechanism that does not exist.
void expectRefused(const Fixture& f, const std::vector<TRAC_IK::JointCoupling>& description,
                   const std::string& joint_name)
{
  const TRAC_IK::JointCouplings couplings(description);
  ASSERT_FALSE(couplings.valid()) << "this description must not be accepted";
  EXPECT_NE(couplings.error().find(joint_name), std::string::npos)
      << "the reason must name the offending joint; got: " << couplings.error();

  TRAC_IK::TRAC_IK ik(f.chain, f.lb, f.ub, couplings);
  EXPECT_FALSE(ik.isInitialized());
  EXPECT_EQ(ik.initializationError(), couplings.error());

  // ...and it stays refused per call, rather than answering as if nothing were wrong.
  KDL::JntArray seed(f.chain.getNrOfJoints()), sol;
  EXPECT_LT(ik.CartToJnt(seed, KDL::Frame::Identity(), sol, defaultQuery()), 0);
}

// The reduced Jacobian is the derivative of the tip pose with respect to the ACTIVE joints, so the
// honest check is against forward kinematics itself rather than against a restatement of the fold.
// (foldJacobian is the verb CONTEXT.md uses for the operation; the object it produces is the
// reduced Jacobian.)
void expectReducedJacobianMatchesFiniteDifferences(const Fixture& f, const TRAC_IK::JointCouplings& c,
                                                  const KDL::JntArray& reduced)
{
  KDL::JntArray full;
  c.expand(reduced, full);

  KDL::ChainJntToJacSolver jacsolver(f.chain);
  KDL::Jacobian jac(f.chain.getNrOfJoints());
  ASSERT_GE(jacsolver.JntToJac(full, jac), 0);

  Eigen::MatrixXd reduced_jac;
  c.foldJacobian(jac, reduced_jac);
  ASSERT_EQ(reduced_jac.rows(), 6);
  ASSERT_EQ(static_cast<unsigned int>(reduced_jac.cols()), c.reducedSize());

  // Central differences, and not a smaller step: KDL's GetRot reads any rotation below about 1e-6
  // rad as none at all, so a forward difference fine enough to make the truncation error negligible
  // reports every angular column as zero and the test passes or fails for the wrong reason.
  const double h = 1e-4;
  for (unsigned int k = 0; k < c.reducedSize(); ++k)
  {
    KDL::JntArray behind = reduced, ahead = reduced;
    behind(k) -= h;
    ahead(k) += h;
    KDL::JntArray behind_full, ahead_full;
    c.expand(behind, behind_full);
    c.expand(ahead, ahead_full);
    const KDL::Frame from = f.fk(behind_full), to = f.fk(ahead_full);

    const KDL::Vector dp = (to.p - from.p) / (2 * h);
    // KDL expresses the Jacobian's angular part in the base frame, so the rotation difference has
    // to be taken there too -- tip-frame it would be right only where the tip happens to be aligned.
    const KDL::Vector dr = (to.M * from.M.Inverse()).GetRot() / (2 * h);
    for (int axis = 0; axis < 3; ++axis)
    {
      EXPECT_NEAR(reduced_jac(axis, k), dp[axis], 1e-5) << "linear axis " << axis << ", active joint " << k;
      EXPECT_NEAR(reduced_jac(axis + 3, k), dr[axis], 1e-5) << "angular axis " << axis << ", active joint " << k;
    }
  }
}

}  // namespace

TEST(TracIkLibCouplings, UncoupledChainConstructsExactlyAsBefore)
{
  Fixture f("arm6.urdf", "base_link", "tool_link");
  TRAC_IK::TRAC_IK plain(f.chain, f.lb, f.ub);
  TRAC_IK::TRAC_IK described(f.chain, f.lb, f.ub, TRAC_IK::JointCouplings(couplingsOf(f)));
  ASSERT_TRUE(plain.isInitialized());
  ASSERT_TRUE(described.isInitialized());
  EXPECT_TRUE(plain.initializationError().empty());

  // An uncoupled chain has nothing to tighten, whether the description is defaulted or spelled out.
  KDL::JntArray a_lb, a_ub, b_lb, b_ub;
  ASSERT_TRUE(plain.getKDLLimits(a_lb, a_ub));
  ASSERT_TRUE(described.getKDLLimits(b_lb, b_ub));
  for (unsigned int i = 0; i < f.chain.getNrOfJoints(); ++i)
  {
    EXPECT_DOUBLE_EQ(a_lb(i), f.lb(i)) << f.joint_names[i];
    EXPECT_DOUBLE_EQ(a_ub(i), f.ub(i)) << f.joint_names[i];
    EXPECT_DOUBLE_EQ(b_lb(i), f.lb(i)) << f.joint_names[i];
    EXPECT_DOUBLE_EQ(b_ub(i), f.ub(i)) << f.joint_names[i];
  }

  const TRAC_IK::JointCouplings couplings(couplingsOf(f));
  EXPECT_EQ(couplings.reducedSize(), f.chain.getNrOfJoints()) << "every joint of arm6 is active";
}

TEST(TracIkLibCouplings, MimicArmEffectiveBoundsAreSignAware)
{
  Fixture f("mimic_arm.urdf", "base_link", "tool_link");
  const TRAC_IK::JointCouplings couplings(couplingsOf(f));
  ASSERT_TRUE(couplings.valid()) << couplings.error();
  EXPECT_EQ(couplings.reducedSize(), 3u) << "4 chain joints, j3 following j2";

  TRAC_IK::TRAC_IK ik(f.chain, f.lb, f.ub, couplings);
  ASSERT_TRUE(ik.isInitialized()) << ik.initializationError();
  KDL::JntArray lb, ub;
  ASSERT_TRUE(ik.getKDLLimits(lb, ub));

  // j3 = -0.5 * j2 + 0.3 over j3's own [-0.2, 0.8]. Mapped back that is [-1.0, 1.0] -- the negative
  // multiplier swaps the ends, so getting the sign wrong gives [1.0, -1.0] or an untightened j2.
  const int j2 = f.indexOf("j2"), j3 = f.indexOf("j3");
  EXPECT_NEAR(lb(j2), -1.0, 1e-12) << "j2's lower bound must tighten from -1.5";
  EXPECT_NEAR(ub(j2), 1.0, 1e-12) << "j2's upper bound must tighten from 1.5";
  // ...and j3 can only take what j2's effective interval maps onto, which here is its own range.
  EXPECT_NEAR(lb(j3), -0.2, 1e-12);
  EXPECT_NEAR(ub(j3), 0.8, 1e-12);

  const int j1 = f.indexOf("j1"), j4 = f.indexOf("j4");
  EXPECT_DOUBLE_EQ(lb(j1), f.lb(j1)) << "an uncoupled joint is left alone";
  EXPECT_DOUBLE_EQ(ub(j4), f.ub(j4));
}

TEST(TracIkLibCouplings, CraneEffectiveBoundsAreItsOwn)
{
  Fixture f("crane.urdf", "base_link", "jib_ext_link");
  const TRAC_IK::JointCouplings couplings(couplingsOf(f));
  ASSERT_TRUE(couplings.valid()) << couplings.error();
  EXPECT_EQ(couplings.reducedSize(), 5u) << "9 chain joints, 4 of them mimic joints";

  TRAC_IK::TRAC_IK ik(f.chain, f.lb, f.ub, couplings);
  ASSERT_TRUE(ik.isInitialized()) << ik.initializationError();
  KDL::JntArray lb, ub;
  ASSERT_TRUE(ik.getKDLLimits(lb, ub));

  // The crane's couplings are all multiplier 1, offset 0, onto stages at least as long as the one
  // they follow, so no ACTIVE joint narrows: the intersection is the joint's own interval. A
  // tightening that fired here would be tightening too eagerly, which is the failure the crane is
  // the only fixture positioned to catch.
  for (unsigned int i = 0; i < f.chain.getNrOfJoints(); ++i)
  {
    if (couplings.isMimic(i))
      continue;
    EXPECT_DOUBLE_EQ(lb(i), f.lb(i)) << f.joint_names[i];
    EXPECT_DOUBLE_EQ(ub(i), f.ub(i)) << f.joint_names[i];
  }
  EXPECT_TRUE(f.unbounded(f.indexOf("turret_rotation"))) << "nothing follows the turret, so it stays continuous";
  EXPECT_DOUBLE_EQ(ub(f.indexOf("main_boom_ext")), 1.918);
  EXPECT_DOUBLE_EQ(ub(f.indexOf("jib_ext")), 1.370);

  // The mimic joints do narrow, in the one place the crane has a mismatch: jib_ext_2's own limit is
  // 1.918, but it is equal to jib_ext, which stops at 1.370, so 1.918 is a reach it never has. The
  // three main boom stages follow a stage of their own length and keep theirs.
  EXPECT_DOUBLE_EQ(ub(f.indexOf("jib_ext_2")), 1.370) << "a mimic joint cannot outrun the joint it follows";
  for (const char* stage : { "main_boom_ext_2", "main_boom_ext_3", "main_boom_ext_4" })
  {
    EXPECT_DOUBLE_EQ(lb(f.indexOf(stage)), 0.0) << stage;
    EXPECT_DOUBLE_EQ(ub(f.indexOf(stage)), 1.918) << stage;
  }
}

// A continuous joint whose mimic joint is bounded is not continuous: its range is finite, and the
// restarts have to sample inside it. No fixture robot has that shape, so the coupling is
// declared over the crane's chain -- the bound arithmetic is what is under test, not the crane.
TEST(TracIkLibCouplings, ContinuousMimickedJointReclassifiesAsBounded)
{
  Fixture f("crane.urdf", "base_link", "jib_ext_link");
  const int turret = f.indexOf("turret_rotation"), lift = f.indexOf("main_boom_lift");
  ASSERT_TRUE(f.unbounded(turret)) << "the turret is continuous as the fixture stands";

  std::vector<TRAC_IK::JointCoupling> description = couplingsOf(f);
  description[lift].mimicked_index = turret;
  description[lift].multiplier = 1.0;
  description[lift].offset = 0.0;

  TRAC_IK::TRAC_IK ik(f.chain, f.lb, f.ub, TRAC_IK::JointCouplings(description));
  ASSERT_TRUE(ik.isInitialized()) << ik.initializationError();
  KDL::JntArray lb, ub;
  ASSERT_TRUE(ik.getKDLLimits(lb, ub));

  EXPECT_DOUBLE_EQ(lb(turret), f.lb(lift)) << "the lift's own lower bound is now the turret's";
  EXPECT_DOUBLE_EQ(ub(turret), f.ub(lift));
  EXPECT_LT(ub(turret), std::numeric_limits<float>::max()) << "the turret is no longer unbounded";

  // The reclassification, observed rather than asserted about: a joint still treated as continuous
  // is wrapped to within a revolution of the seed and left there, so a solution would come back
  // outside the interval the couplings just proved it cannot leave.
  TRAC_IK::Query q = defaultQuery();
  q.tolerance_bounds.rot.x(std::numeric_limits<float>::max());
  q.tolerance_bounds.rot.y(std::numeric_limits<float>::max());
  q.tolerance_bounds.rot.z(std::numeric_limits<float>::max());

  std::mt19937 rng(41);
  int solved = 0;
  for (int n = 0; n < 20; ++n)
  {
    KDL::JntArray inside(f.chain.getNrOfJoints());
    for (unsigned int i = 0; i < f.chain.getNrOfJoints(); ++i)
      inside(i) = std::uniform_real_distribution<double>(lb(i), ub(i))(rng);
    KDL::JntArray seed = f.randomConfig(rng), sol;
    if (ik.CartToJnt(seed, f.fk(inside), sol, q) < 0)
      continue;
    ++solved;
    EXPECT_GE(sol(turret), lb(turret) - 1e-6) << "the turret is bounded now";
    EXPECT_LE(sol(turret), ub(turret) + 1e-6) << "the turret is bounded now";
  }
  EXPECT_GT(solved, 0) << "the narrowed crane must still reach some of its own poses";
}

TEST(TracIkLibCouplings, ZeroMultiplierPinsTheJoint)
{
  Fixture f("mimic_arm.urdf", "base_link", "tool_link");
  const int j2 = f.indexOf("j2"), j3 = f.indexOf("j3");

  // <mimic multiplier="0" offset="c"/> is well-formed URDF meaning "held at c", and real models use
  // it. It is a pinned joint, not a refusal.
  std::vector<TRAC_IK::JointCoupling> description = couplingsOf(f);
  description[j3].multiplier = 0.0;
  description[j3].offset = 0.5;

  TRAC_IK::TRAC_IK ik(f.chain, f.lb, f.ub, TRAC_IK::JointCouplings(description));
  ASSERT_TRUE(ik.isInitialized()) << ik.initializationError();
  KDL::JntArray lb, ub;
  ASSERT_TRUE(ik.getKDLLimits(lb, ub));
  EXPECT_DOUBLE_EQ(lb(j3), 0.5) << "pinned: a single point";
  EXPECT_DOUBLE_EQ(ub(j3), 0.5);
  // A pinned joint takes no value from the joint it follows, so it bounds it not at all.
  EXPECT_DOUBLE_EQ(lb(j2), f.lb(j2)) << "a pinned mimic contributes no bound";
  EXPECT_DOUBLE_EQ(ub(j2), f.ub(j2));

  KDL::JntArray reduced(3), full;
  reduced(0) = 0.1;
  reduced(1) = 0.9;
  reduced(2) = -0.4;
  TRAC_IK::JointCouplings(description).expand(reduced, full);
  EXPECT_DOUBLE_EQ(full(j3), 0.5) << "expand pins it too, whatever j2 is doing";
}

// The pin itself can be impossible, and that is a mechanism no configuration satisfies -- refused,
// naming the joint, like any other. It is the zero multiplier that is supported, not a contradiction.
TEST(TracIkLibCouplings, APinOutsideTheJointsOwnBoundsIsRefused)
{
  Fixture f("mimic_arm.urdf", "base_link", "tool_link");
  std::vector<TRAC_IK::JointCoupling> description = couplingsOf(f);
  description[f.indexOf("j3")].multiplier = 0.0;
  description[f.indexOf("j3")].offset = 2.0;  // j3's own bounds are [-0.2, 0.8]

  const TRAC_IK::JointCouplings couplings(description);
  ASSERT_TRUE(couplings.valid()) << "the description is well-formed; the mechanism is not";
  TRAC_IK::TRAC_IK ik(f.chain, f.lb, f.ub, couplings);
  EXPECT_FALSE(ik.isInitialized());
  EXPECT_NE(ik.initializationError().find("j3"), std::string::npos) << ik.initializationError();
}

TEST(TracIkLibCouplings, AMimicOfAMimicIsRefused)
{
  for (const CoupledFixture& c : kCoupledFixtures)
  {
    Fixture f(c.urdf, "base_link", c.tip);
    std::vector<TRAC_IK::JointCoupling> description = couplingsOf(f);
    // Turn the joint that is followed into a follower of its own mimic joint.
    description[f.indexOf(c.mimicked)].mimicked_index = f.indexOf(c.mimic);
    expectRefused(f, description, c.mimicked);
  }
}

TEST(TracIkLibCouplings, AMimickedJointOutsideTheChainIsRefused)
{
  for (const CoupledFixture& c : kCoupledFixtures)
  {
    Fixture f(c.urdf, "base_link", c.tip);
    std::vector<TRAC_IK::JointCoupling> description = couplingsOf(f);
    // Treating it as a constant would silently move the tip whenever the real joint moved.
    description[f.indexOf(c.mimic)].mimicked_index = static_cast<int>(f.chain.getNrOfJoints());
    expectRefused(f, description, c.mimic);
  }
}

TEST(TracIkLibCouplings, AVariableCountOtherThanOneIsRefused)
{
  for (const CoupledFixture& c : kCoupledFixtures)
  {
    Fixture f(c.urdf, "base_link", c.tip);
    std::vector<TRAC_IK::JointCoupling> description = couplingsOf(f);
    // A planar or floating joint that survived kdl_parser: more than one variable behind one index.
    // It is checked for every chain joint, active ones included, not only for the mimic joints.
    description[f.indexOf(c.mimicked)].variable_count = 3;
    expectRefused(f, description, c.mimicked);
  }
}

TEST(TracIkLibCouplings, ANonFiniteMultiplierIsRefused)
{
  for (const CoupledFixture& c : kCoupledFixtures)
  {
    Fixture f(c.urdf, "base_link", c.tip);
    for (const double bad : { std::numeric_limits<double>::quiet_NaN(),
                              std::numeric_limits<double>::infinity() })
    {
      std::vector<TRAC_IK::JointCoupling> description = couplingsOf(f);
      description[f.indexOf(c.mimic)].multiplier = bad;
      expectRefused(f, description, c.mimic);
    }
  }
}

// Every operation is a no-op on a rejected description, so a caller who validates by hand and gets
// it wrong reads nothing it never built. Only TRAC_IK refuses outright.
TEST(TracIkLibCouplings, ARejectedDescriptionIsInert)
{
  Fixture f("crane.urdf", "base_link", "jib_ext_link");
  std::vector<TRAC_IK::JointCoupling> description = couplingsOf(f);
  description[f.indexOf("jib_ext_2")].mimicked_index = static_cast<int>(f.chain.getNrOfJoints());
  const TRAC_IK::JointCouplings couplings(description);
  ASSERT_FALSE(couplings.valid());

  EXPECT_EQ(couplings.reducedSize(), 0u);
  EXPECT_TRUE(couplings.activeIndices().empty());

  KDL::JntArray reduced, full, lb = f.lb, ub = f.ub;
  couplings.expand(reduced, full);
  couplings.reduce(full, reduced);
  KDL::Jacobian jac(f.chain.getNrOfJoints());
  Eigen::MatrixXd reduced_jac;
  couplings.foldJacobian(jac, reduced_jac);
  std::string why;
  EXPECT_FALSE(couplings.tighten(lb, ub, why));
  EXPECT_EQ(why, couplings.error());
}

TEST(TracIkLibCouplings, ExpandFillsMimicEntriesAndReduceDropsThem)
{
  for (const char* fixture : { "crane.urdf", "mimic_arm.urdf" })
  {
    const bool is_crane = std::string(fixture) == "crane.urdf";
    Fixture f(fixture, "base_link", is_crane ? "jib_ext_link" : "tool_link");
    const TRAC_IK::JointCouplings couplings(couplingsOf(f));
    ASSERT_TRUE(couplings.valid()) << couplings.error();

    std::mt19937 rng(31);
    // A full configuration whose mimic entries are deliberately WRONG: reduce keeps only what the
    // solver chooses, so expanding again is exactly the repair an incoming seed needs.
    KDL::JntArray full = f.randomConfig(rng), reduced, rebuilt;
    couplings.reduce(full, reduced);
    ASSERT_EQ(reduced.rows(), couplings.reducedSize());
    couplings.expand(reduced, rebuilt);
    ASSERT_EQ(rebuilt.rows(), f.chain.getNrOfJoints());

    for (unsigned int k = 0; k < couplings.reducedSize(); ++k)
      EXPECT_DOUBLE_EQ(rebuilt(couplings.activeIndices()[k]), full(couplings.activeIndices()[k]))
          << "an active joint's value is the solver's and must survive the round trip";
    expectMimicCouplings(f, rebuilt);
  }
}

TEST(TracIkLibCouplings, ReducedJacobianIsTheDerivativeWithRespectToTheActiveJoints)
{
  {
    Fixture f("crane.urdf", "base_link", "jib_ext_link");
    const TRAC_IK::JointCouplings couplings(couplingsOf(f));
    ASSERT_TRUE(couplings.valid()) << couplings.error();
    std::mt19937 rng(32);
    for (int n = 0; n < 5; ++n)
    {
      KDL::JntArray reduced;
      couplings.reduce(f.mimicConsistentConfig(rng), reduced);
      expectReducedJacobianMatchesFiniteDifferences(f, couplings, reduced);
    }
  }
  {
    // The sign of the fold: mimic_arm's multiplier is negative, so a column that added the mimic
    // joint's contribution rather than subtracting it is wrong here and nowhere else.
    Fixture f("mimic_arm.urdf", "base_link", "tool_link");
    const TRAC_IK::JointCouplings couplings(couplingsOf(f));
    ASSERT_TRUE(couplings.valid()) << couplings.error();
    std::mt19937 rng(33);
    for (int n = 0; n < 5; ++n)
    {
      KDL::JntArray reduced;
      couplings.reduce(f.mimicConsistentConfig(rng), reduced);
      expectReducedJacobianMatchesFiniteDifferences(f, couplings, reduced);
    }
  }
}

// The zero multiplier again, on the crane's prismatic couplings: a pinned joint is a pinned joint
// whatever the joint is made of, and the crane is where a stage pinned mid-travel is plausible.
TEST(TracIkLibCouplings, ZeroMultiplierPinsAPrismaticStageToo)
{
  Fixture f("crane.urdf", "base_link", "jib_ext_link");
  const int pinned = f.indexOf("main_boom_ext_2"), driver = f.indexOf("main_boom_ext");

  std::vector<TRAC_IK::JointCoupling> description = couplingsOf(f);
  description[pinned].multiplier = 0.0;
  description[pinned].offset = 0.5;

  TRAC_IK::TRAC_IK ik(f.chain, f.lb, f.ub, TRAC_IK::JointCouplings(description));
  ASSERT_TRUE(ik.isInitialized()) << ik.initializationError();
  KDL::JntArray lb, ub;
  ASSERT_TRUE(ik.getKDLLimits(lb, ub));
  EXPECT_DOUBLE_EQ(lb(pinned), 0.5);
  EXPECT_DOUBLE_EQ(ub(pinned), 0.5);
  // The other two stages still follow main_boom_ext at multiplier 1, so it keeps its own range.
  EXPECT_DOUBLE_EQ(lb(driver), f.lb(driver));
  EXPECT_DOUBLE_EQ(ub(driver), f.ub(driver));
}

// A query may narrow the search (ticket 03), but it cannot widen the mechanism: the couplings hold
// for a per-call bound pair too. Without this a caller handing back the joints' own bounds would
// undo the tightening the constructor did, for that call only, and never be told.
TEST(TracIkLibCouplings, PerCallJointBoundsAreTightenedThroughTheCouplingsToo)
{
  Fixture f("mimic_arm.urdf", "base_link", "tool_link");
  const int j2 = f.indexOf("j2");
  TRAC_IK::TRAC_IK ik(f.chain, f.lb, f.ub, TRAC_IK::JointCouplings(couplingsOf(f)));
  ASSERT_TRUE(ik.isInitialized()) << ik.initializationError();

  // The fixture's own, UNtightened bounds, handed over as this call's: j2 asks for [-1.5, 1.5]
  // where the coupling allows only [-1.0, 1.0].
  TRAC_IK::Query q = defaultQuery();
  q.q_min = f.lb;
  q.q_max = f.ub;
  q.tolerance_bounds.rot.x(std::numeric_limits<float>::max());
  q.tolerance_bounds.rot.y(std::numeric_limits<float>::max());
  q.tolerance_bounds.rot.z(std::numeric_limits<float>::max());

  std::mt19937 rng(42);
  int solved = 0;
  for (int n = 0; n < 40; ++n)
  {
    const KDL::Frame target = f.fk(f.mimicConsistentConfig(rng));
    KDL::JntArray seed = f.randomConfig(rng), sol;
    if (ik.CartToJnt(seed, target, sol, q) < 0)
      continue;
    ++solved;
    EXPECT_GE(sol(j2), -1.0 - 1e-6) << "the query's wider bound must not survive the couplings";
    EXPECT_LE(sol(j2), 1.0 + 1e-6) << "the query's wider bound must not survive the couplings";
  }
  EXPECT_GT(solved, 0) << "the coupled arm must still answer this query";
}

// ...and a per-call pair that leaves the couplings nothing is refused per call, not answered.
TEST(TracIkLibCouplings, PerCallJointBoundsWithNoSatisfiableConfigurationAreRefused)
{
  Fixture f("mimic_arm.urdf", "base_link", "tool_link");
  TRAC_IK::TRAC_IK ik(f.chain, f.lb, f.ub, TRAC_IK::JointCouplings(couplingsOf(f)));
  ASSERT_TRUE(ik.isInitialized()) << ik.initializationError();

  TRAC_IK::Query q = defaultQuery();
  q.q_min = f.lb;
  q.q_max = f.ub;
  // j2 above what j3's own bounds map back to (1.0), so the two intervals do not meet.
  q.q_min(f.indexOf("j2")) = 1.2;
  q.q_max(f.indexOf("j2")) = 1.4;

  std::mt19937 rng(43);
  KDL::JntArray seed = f.randomConfig(rng), sol;
  // -1, the refusal, and not -3: the query is rejected before any search, so "no solution found"
  // would mean the bounds had been accepted and simply not worked out.
  EXPECT_EQ(ik.CartToJnt(seed, f.fk(f.mimicConsistentConfig(rng)), sol, q), -1);

  // The mechanism is untouched by a query it refused.
  KDL::JntArray lb, ub;
  ASSERT_TRUE(ik.getKDLLimits(lb, ub));
  EXPECT_NEAR(ub(f.indexOf("j2")), 1.0, 1e-12);
}
