// PROTOTYPE HARNESS (wayfinder ticket 02) - throwaway, not production code.
//
// Seam under test: TRAC_IK::TRAC_IK::CartToJnt on a KDL chain built from a URDF string.
// Assertions are structural on purpose: the solver's RNG is not seedable until ticket 10, so no test
// may expect a particular configuration. What must hold for ANY valid solution is:
//   - FK of the solution reproduces the target within epsilon (tolerance bounds applied)
//   - every joint value lies inside its limits
//   - the solve rate over a sample of reachable targets clears a generous floor
// Target poses are generated by forward kinematics from a random full configuration, so every target
// is reachable by construction; the expected value comes from KDL's FK solver, not from the IK code.

#include <gtest/gtest.h>

#include <kdl/chainfksolverpos_recursive.hpp>
#include <kdl_parser/kdl_parser.hpp>
#include <trac_ik/trac_ik.hpp>
// Jazzy's urdf 2.10.1 has no <urdf/model.hpp>; on Kilted and Rolling <urdf/model.h> is a shim that
// warns. Delete this guard, keeping the .hpp, when Jazzy reaches EOL (May 2029).
#if __has_include(<urdf/model.hpp>)
#include <urdf/model.hpp>
#else
#include <urdf/model.h>
#endif

#include <fstream>
#include <limits>
#include <random>
#include <sstream>
#include <string>
#include <vector>

namespace
{

constexpr double kEps = 1e-5;       // solver convergence threshold
constexpr double kPosTol = 1e-3;    // metres, FK round-trip
constexpr double kRotTol = 1e-3;    // radians, FK round-trip
constexpr int kSamples = 200;
constexpr double kSolveRateFloor = 0.90;  // generous: tighten once ticket 10 seeds the RNG

std::string readFixture(const std::string& name)
{
  std::ifstream in(std::string(TRAC_IK_TEST_FIXTURE_DIR) + "/" + name);
  EXPECT_TRUE(in.good()) << "fixture not found: " << name;
  std::stringstream ss;
  ss << in.rdbuf();
  return ss.str();
}

// The chain, its limits, and an FK solver: everything a library-seam test needs.
struct Fixture
{
  urdf::Model model;
  KDL::Chain chain;
  KDL::JntArray lb, ub;
  std::vector<std::string> joint_names;

  Fixture(const std::string& urdf_file, const std::string& base, const std::string& tip)
  {
    const std::string xml = readFixture(urdf_file);
    EXPECT_TRUE(model.initString(xml));
    KDL::Tree tree;
    EXPECT_TRUE(kdl_parser::treeFromString(xml, tree));
    EXPECT_TRUE(tree.getChain(base, tip, chain));

    lb.resize(chain.getNrOfJoints());
    ub.resize(chain.getNrOfJoints());
    unsigned int i = 0;
    for (const auto& seg : chain.segments)
    {
      auto joint = model.getJoint(seg.getJoint().getName());
      if (!joint || joint->type == urdf::Joint::UNKNOWN || joint->type == urdf::Joint::FIXED)
        continue;
      joint_names.push_back(joint->name);
      // Mirrors trac_ik.cpp: a continuous joint is reported as unbounded via float sentinels.
      if (joint->type == urdf::Joint::CONTINUOUS)
      {
        lb(i) = std::numeric_limits<float>::lowest();
        ub(i) = std::numeric_limits<float>::max();
      }
      else
      {
        lb(i) = joint->limits->lower;
        ub(i) = joint->limits->upper;
      }
      ++i;
    }
    EXPECT_EQ(i, chain.getNrOfJoints());
  }

  bool unbounded(unsigned int i) const
  {
    return ub(i) >= std::numeric_limits<float>::max() && lb(i) <= std::numeric_limits<float>::lowest();
  }

  KDL::Frame fk(const KDL::JntArray& q) const
  {
    KDL::ChainFkSolverPos_recursive solver(chain);
    KDL::Frame f;
    EXPECT_GE(solver.JntToCart(q, f), 0);
    return f;
  }

  // A random full configuration inside the limits; continuous joints sample [-pi, pi].
  KDL::JntArray randomConfig(std::mt19937& rng) const
  {
    KDL::JntArray q(chain.getNrOfJoints());
    for (unsigned int i = 0; i < chain.getNrOfJoints(); ++i)
    {
      const double lo = unbounded(i) ? -M_PI : lb(i);
      const double hi = unbounded(i) ? M_PI : ub(i);
      q(i) = std::uniform_real_distribution<double>(lo, hi)(rng);
    }
    return q;
  }
};

void expectWithinLimits(const Fixture& f, const KDL::JntArray& q)
{
  for (unsigned int i = 0; i < q.rows(); ++i)
  {
    if (f.unbounded(i))
      continue;
    EXPECT_GE(q(i), f.lb(i) - 1e-6) << "joint " << f.joint_names[i] << " below its lower limit";
    EXPECT_LE(q(i), f.ub(i) + 1e-6) << "joint " << f.joint_names[i] << " above its upper limit";
  }
}

double positionError(const KDL::Frame& a, const KDL::Frame& b)
{
  return (a.p - b.p).Norm();
}

double rotationError(const KDL::Frame& a, const KDL::Frame& b)
{
  return (a.M.Inverse() * b.M).GetRot().Norm();
}

}  // namespace

// ---------------------------------------------------------------------------------------------
// arm6: a conventional 6-DOF arm, no mimic joints. Keeps the suite honest about the regressions
// the crane (5 active DOF, position-only) cannot show.
// ---------------------------------------------------------------------------------------------

TEST(TracIkLib, Arm6FullPoseRoundTrip)
{
  Fixture f("arm6.urdf", "base_link", "tool_link");
  TRAC_IK::TRAC_IK ik(f.chain, f.lb, f.ub, 0.05, kEps, TRAC_IK::Speed);

  std::mt19937 rng(1);  // test-side determinism: the TARGETS repeat, the solver's search does not
  int solved = 0;
  for (int n = 0; n < kSamples; ++n)
  {
    const KDL::Frame target = f.fk(f.randomConfig(rng));
    KDL::JntArray seed = f.randomConfig(rng), sol;
    if (ik.CartToJnt(seed, target, sol) < 0)
      continue;
    ++solved;
    expectWithinLimits(f, sol);
    const KDL::Frame reached = f.fk(sol);
    EXPECT_LT(positionError(target, reached), kPosTol);
    EXPECT_LT(rotationError(target, reached), kRotTol);
  }
  EXPECT_GE(static_cast<double>(solved) / kSamples, kSolveRateFloor)
      << "solved " << solved << " of " << kSamples;
}

TEST(TracIkLib, Arm6PositionOnlyToleranceFreesOrientation)
{
  Fixture f("arm6.urdf", "base_link", "tool_link");
  TRAC_IK::TRAC_IK ik(f.chain, f.lb, f.ub, 0.05, kEps, TRAC_IK::Speed);

  // Infinite rotational tolerance bounds: the three orientation components are free.
  KDL::Twist bounds = KDL::Twist::Zero();
  bounds.rot.x(std::numeric_limits<float>::max());
  bounds.rot.y(std::numeric_limits<float>::max());
  bounds.rot.z(std::numeric_limits<float>::max());

  std::mt19937 rng(2);
  int solved = 0;
  for (int n = 0; n < kSamples; ++n)
  {
    const KDL::Frame target = f.fk(f.randomConfig(rng));
    KDL::JntArray seed = f.randomConfig(rng), sol;
    if (ik.CartToJnt(seed, target, sol, bounds) < 0)
      continue;
    ++solved;
    expectWithinLimits(f, sol);
    // Position must still be met; orientation is explicitly not asserted.
    EXPECT_LT(positionError(target, f.fk(sol)), kPosTol);
  }
  EXPECT_GE(static_cast<double>(solved) / kSamples, kSolveRateFloor)
      << "solved " << solved << " of " << kSamples;
}

TEST(TracIkLib, Arm6ContinuousJointsAreUnbounded)
{
  Fixture f("arm6.urdf", "base_link", "tool_link");
  KDL::JntArray lb, ub;
  TRAC_IK::TRAC_IK ik(f.chain, f.lb, f.ub, 0.05, kEps, TRAC_IK::Speed);
  ASSERT_TRUE(ik.getKDLLimits(lb, ub));
  for (unsigned int i = 0; i < f.joint_names.size(); ++i)
  {
    const bool is_continuous = f.model.getJoint(f.joint_names[i])->type == urdf::Joint::CONTINUOUS;
    EXPECT_EQ(is_continuous, f.unbounded(i)) << "joint " << f.joint_names[i];
  }
}

// ---------------------------------------------------------------------------------------------
// The crane: 9 chain joints, 4 of them mimic joints, 5 active. Today the library has no notion of
// a mimic joint, so it treats all 9 as active. The coupling test below is the RED one ticket 04
// turns green.
// ---------------------------------------------------------------------------------------------

TEST(TracIkLib, CraneChainShape)
{
  Fixture f("crane.urdf", "base_link", "jib_ext_link");
  EXPECT_EQ(f.chain.getNrOfJoints(), 9u) << "the crane chain has 9 joints with variables";
  int mimics = 0;
  for (const auto& name : f.joint_names)
    if (f.model.getJoint(name)->mimic)
      ++mimics;
  EXPECT_EQ(mimics, 4) << "4 of them are mimic joints";
}

TEST(TracIkLib, CraneSolutionRespectsMimicCoupling)
{
  Fixture f("crane.urdf", "base_link", "jib_ext_link");
  // Distance, not Speed, and deliberately so: in Speed mode the KDL branch answers in ~1 ms with a
  // solution whose four parallel prismatic joints happen to be equal, so the coupling looks intact
  // and this test goes green for a reason that has nothing to do with mimic support. Distance
  // collects solutions for the whole timeout and the winner violates the coupling outright.
  TRAC_IK::TRAC_IK ik(f.chain, f.lb, f.ub, 0.05, kEps, TRAC_IK::Distance);

  // A mimic-consistent full configuration, so the target is reachable under the coupling.
  KDL::JntArray q(f.chain.getNrOfJoints());
  std::mt19937 rng(3);
  for (unsigned int i = 0; i < f.joint_names.size(); ++i)
  {
    const auto joint = f.model.getJoint(f.joint_names[i]);
    if (joint->mimic)
      continue;
    const double lo = f.unbounded(i) ? -M_PI : f.lb(i);
    const double hi = f.unbounded(i) ? M_PI : f.ub(i);
    q(i) = std::uniform_real_distribution<double>(lo, hi)(rng);
  }
  for (unsigned int i = 0; i < f.joint_names.size(); ++i)
  {
    const auto joint = f.model.getJoint(f.joint_names[i]);
    if (!joint->mimic)
      continue;
    for (unsigned int j = 0; j < f.joint_names.size(); ++j)
      if (f.joint_names[j] == joint->mimic->joint_name)
        q(i) = joint->mimic->multiplier * q(j) + joint->mimic->offset;
  }

  const KDL::Frame target = f.fk(q);
  // NOT a zero seed. The four main_boom_ext* joints are parallel prismatic joints, so their Jacobian
  // columns are identical; from an all-equal seed a pseudo-inverse step moves them by equal amounts
  // and the mimic violation stays invisible. An asymmetric seed is what exposes it.
  KDL::JntArray seed = f.randomConfig(rng), sol;
  ASSERT_GE(ik.CartToJnt(seed, target, sol), 0) << "no solution for a reachable crane pose";
  EXPECT_LT(positionError(target, f.fk(sol)), kPosTol) << "the 9 free joints do reach the target";
  expectWithinLimits(f, sol);

  // RED until ticket 04: the solver chooses all 9 joints independently, so the coupling is broken.
  for (unsigned int i = 0; i < f.joint_names.size(); ++i)
  {
    const auto joint = f.model.getJoint(f.joint_names[i]);
    if (!joint->mimic)
      continue;
    for (unsigned int j = 0; j < f.joint_names.size(); ++j)
      if (f.joint_names[j] == joint->mimic->joint_name)
        EXPECT_NEAR(sol(i), joint->mimic->multiplier * sol(j) + joint->mimic->offset, 1e-6)
            << f.joint_names[i] << " must follow " << f.joint_names[j];
  }
}

// ---------------------------------------------------------------------------------------------
// arm7 (wayfinder ticket 22): a redundant 7R arm. Against a full-pose goal its 6x7 Jacobian has a
// one-dimensional null space, a third regime the suite lacked -- the crane is rank-deficient and
// arm6 is square. Redundancy is what TRAC-IK's own audience has.
// ---------------------------------------------------------------------------------------------

TEST(TracIkLib, Arm7FullPoseRoundTrip)
{
  Fixture f("arm7.urdf", "base_link", "tool_link");
  ASSERT_EQ(f.chain.getNrOfJoints(), 7u);
  TRAC_IK::TRAC_IK ik(f.chain, f.lb, f.ub, 0.05, kEps, TRAC_IK::Speed);

  std::mt19937 rng(7);
  int solved = 0;
  for (int n = 0; n < kSamples; ++n)
  {
    const KDL::Frame target = f.fk(f.randomConfig(rng));
    KDL::JntArray seed = f.randomConfig(rng), sol;
    if (ik.CartToJnt(seed, target, sol) < 0)
      continue;
    ++solved;
    expectWithinLimits(f, sol);
    const KDL::Frame reached = f.fk(sol);
    EXPECT_LT(positionError(target, reached), kPosTol);
    EXPECT_LT(rotationError(target, reached), kRotTol);
  }
  EXPECT_GE(static_cast<double>(solved) / kSamples, kSolveRateFloor)
      << "solved " << solved << " of " << kSamples;
}

TEST(TracIkLib, Arm7PositionOnlyToleranceFreesOrientation)
{
  Fixture f("arm7.urdf", "base_link", "tool_link");
  TRAC_IK::TRAC_IK ik(f.chain, f.lb, f.ub, 0.05, kEps, TRAC_IK::Speed);

  KDL::Twist bounds = KDL::Twist::Zero();
  bounds.rot.x(std::numeric_limits<float>::max());
  bounds.rot.y(std::numeric_limits<float>::max());
  bounds.rot.z(std::numeric_limits<float>::max());

  std::mt19937 rng(8);
  int solved = 0;
  for (int n = 0; n < kSamples; ++n)
  {
    const KDL::Frame target = f.fk(f.randomConfig(rng));
    KDL::JntArray seed = f.randomConfig(rng), sol;
    if (ik.CartToJnt(seed, target, sol, bounds) < 0)
      continue;
    ++solved;
    expectWithinLimits(f, sol);
    EXPECT_LT(positionError(target, f.fk(sol)), kPosTol);
  }
  EXPECT_GE(static_cast<double>(solved) / kSamples, kSolveRateFloor)
      << "solved " << solved << " of " << kSamples;
}

// The self-motion witness: one target, many seeds, genuinely different configurations that all
// reach it. This is the property ticket 07's "walk the candidate list against the validity
// callback" leans on and neither existing fixture has (the crane's spare DOF is a coupling, and
// arm6's square Jacobian gives isolated solutions only).
TEST(TracIkLib, Arm7HasANullSpaceOfSolutions)
{
  Fixture f("arm7.urdf", "base_link", "tool_link");
  TRAC_IK::TRAC_IK ik(f.chain, f.lb, f.ub, 0.05, kEps, TRAC_IK::Speed);

  std::mt19937 rng(9);
  const KDL::Frame target = f.fk(f.randomConfig(rng));

  std::vector<KDL::JntArray> found;
  for (int n = 0; n < 20; ++n)
  {
    KDL::JntArray seed = f.randomConfig(rng), sol;
    if (ik.CartToJnt(seed, target, sol) < 0)
      continue;
    ASSERT_LT(positionError(target, f.fk(sol)), kPosTol);
    ASSERT_LT(rotationError(target, f.fk(sol)), kRotTol);
    found.push_back(sol);
  }
  ASSERT_GE(found.size(), 5u) << "the redundant arm should reach one pose from most seeds";

  double widest = 0.0;
  for (size_t a = 0; a < found.size(); ++a)
    for (size_t b = a + 1; b < found.size(); ++b)
    {
      double d = 0.0;
      for (unsigned int i = 0; i < found[a].rows(); ++i)
        d = std::max(d, std::fabs(found[a](i) - found[b](i)));
      widest = std::max(widest, d);
    }
  EXPECT_GT(widest, 0.1) << "distinct solutions for one pose; widest joint spread " << widest;
}
