// Seam under test: TRAC_IK::TRAC_IK::CartToJnt on a KDL chain built from a URDF string.
// Assertions are structural on purpose: the solver's RNG is not seedable until ticket 10, so no test
// may expect a particular configuration. What must hold for ANY valid solution is:
//   - FK of the solution reproduces the target within epsilon (tolerance bounds applied)
//   - every joint value lies inside its limits
//   - the solve rate over a sample of reachable targets clears a generous floor
// Target poses are generated by forward kinematics from a random full configuration, so every target
// is reachable by construction; the expected value comes from KDL's FK solver, not from the IK code.
//
// Four fixtures, shared with the plugin seam and found through the TRAC_IK_TEST_FIXTURE_DIR compile
// definition: the mesh-stripped crane (9 joints, 4 mimic, 5 active), arm6 (a plain 6-DOF arm),
// arm7 (redundant 7R) and mimic_arm (one revolute mimic, negative multiplier, nonzero offset).

#include <gtest/gtest.h>

#include <kdl/chainfksolverpos_recursive.hpp>
#include <kdl_parser/kdl_parser.hpp>
#include <trac_ik/trac_ik.hpp>
// Jazzy's urdf 2.10.1 has no <urdf/model.hpp>; on Kilted and Rolling <urdf/model.h> is a shim that
// warns. Delete this guard, keeping the .hpp, when Jazzy reaches EOL (May 2029).
#if __has_include(<urdf/model.hpp>)
#include <urdf/model.hpp>
#else
#include <urdf/model.h>
#endif

#include <cstdlib>
#include <fstream>
#include <limits>
#include <random>
#include <sstream>
#include <string>
#include <vector>

namespace
{

constexpr double kEps = 1e-5;       // solver convergence threshold
constexpr double kPosTol = 1e-3;    // metres, FK round-trip
constexpr double kRotTol = 1e-3;    // radians, FK round-trip
constexpr int kSamples = 200;
constexpr double kSolveRateFloor = 0.90;  // generous: tighten once ticket 10 seeds the RNG

// The per-solve budget, in seconds. Defaults to MoveIt's own kinematics_solver_timeout, which is
// what a user's robot gets; CI sets TRAC_IK_TEST_SOLVE_BUDGET to a looser value, because a shared
// runner is slower and noisier than the machine these bounds were chosen on and should fail on
// behaviour, not on wall-clock. No test asserts a duration, so raising it can only help a solve --
// up to the target's own ctest timeout, which is why the value is range-checked.
double solveBudget()
{
  static const double budget = []() {
    constexpr double kDefault = 0.05;
    const char* env = std::getenv("TRAC_IK_TEST_SOLVE_BUDGET");
    if (!env)
      return kDefault;
    // strtod, not atof: atof accepts trailing garbage, so "200ms" would parse as a 200-second
    // budget, quietly blow through the target's own 300 s ctest timeout and kill the cell with no
    // hint that the variable is at fault. A mistyped budget must fail as a misconfiguration.
    char* end = nullptr;
    const double parsed = std::strtod(env, &end);
    // Upper bound because the budget multiplies out: the plugin's sampled tests spend it on all 50
    // samples, so 1 s is already 150 s of the target's 300 s ctest TIMEOUT. Past that the cell dies
    // on wall-clock, which is the failure mode this variable exists to prevent.
    const bool ok = end && *end == '\0' && end != env && parsed > 0.0 && parsed <= 1.0;
    EXPECT_TRUE(ok) << "TRAC_IK_TEST_SOLVE_BUDGET must be a bare number of seconds in (0, 1]: " << env;
    return ok ? parsed : kDefault;
  }();
  return budget;
}

// This suite's query: the budget and epsilon every test solves with. Timeout, epsilon, solve type
// and the tolerance bounds live on the query rather than on the solver, so one instance answers
// every sample in a test.
TRAC_IK::Query defaultQuery(TRAC_IK::SolveType type = TRAC_IK::Speed)
{
  TRAC_IK::Query q;
  q.timeout = solveBudget();
  q.epsilon = kEps;
  q.solve_type = type;
  return q;
}

std::string readFixture(const std::string& name)
{
  std::ifstream in(std::string(TRAC_IK_TEST_FIXTURE_DIR) + "/" + name);
  EXPECT_TRUE(in.good()) << "fixture not found: " << name;
  std::stringstream ss;
  ss << in.rdbuf();
  return ss.str();
}

// The chain, its limits, and an FK solver: everything a library-seam test needs.
struct Fixture
{
  urdf::Model model;
  KDL::Chain chain;
  KDL::JntArray lb, ub;
  std::vector<std::string> joint_names;

  Fixture(const std::string& urdf_file, const std::string& base, const std::string& tip)
  {
    const std::string xml = readFixture(urdf_file);
    EXPECT_TRUE(model.initString(xml));
    KDL::Tree tree;
    EXPECT_TRUE(kdl_parser::treeFromString(xml, tree));
    EXPECT_TRUE(tree.getChain(base, tip, chain));

    lb.resize(chain.getNrOfJoints());
    ub.resize(chain.getNrOfJoints());
    unsigned int i = 0;
    for (const auto& seg : chain.segments)
    {
      auto joint = model.getJoint(seg.getJoint().getName());
      if (!joint || joint->type == urdf::Joint::UNKNOWN || joint->type == urdf::Joint::FIXED)
        continue;
      joint_names.push_back(joint->name);
      // Mirrors trac_ik.cpp: a continuous joint is reported as unbounded via float sentinels.
      if (joint->type == urdf::Joint::CONTINUOUS)
      {
        lb(i) = std::numeric_limits<float>::lowest();
        ub(i) = std::numeric_limits<float>::max();
      }
      else
      {
        lb(i) = joint->limits->lower;
        ub(i) = joint->limits->upper;
      }
      ++i;
    }
    EXPECT_EQ(i, chain.getNrOfJoints());
  }

  bool unbounded(unsigned int i) const
  {
    return ub(i) >= std::numeric_limits<float>::max() && lb(i) <= std::numeric_limits<float>::lowest();
  }

  KDL::Frame fk(const KDL::JntArray& q) const
  {
    KDL::ChainFkSolverPos_recursive solver(chain);
    KDL::Frame f;
    EXPECT_GE(solver.JntToCart(q, f), 0);
    return f;
  }

  // A random full configuration inside the limits; continuous joints sample [-pi, pi].
  KDL::JntArray randomConfig(std::mt19937& rng) const
  {
    KDL::JntArray q(chain.getNrOfJoints());
    for (unsigned int i = 0; i < chain.getNrOfJoints(); ++i)
    {
      const double lo = unbounded(i) ? -M_PI : lb(i);
      const double hi = unbounded(i) ? M_PI : ub(i);
      q(i) = std::uniform_real_distribution<double>(lo, hi)(rng);
    }
    return q;
  }

  int indexOf(const std::string& joint_name) const
  {
    for (unsigned int i = 0; i < joint_names.size(); ++i)
      if (joint_names[i] == joint_name)
        return static_cast<int>(i);
    return -1;
  }

  // A random full configuration that satisfies every coupling the URDF declares, so a target built
  // from it is reachable whether or not the solver knows about mimic joints. The sampling interval
  // of a mimicked joint is tightened by the interval its mimic's own limits map back to -- those can
  // be narrower than the multiplier would induce, and mimic_arm's deliberately are. The mapping is
  // sign-aware: a negative multiplier swaps the ends.
  KDL::JntArray mimicConsistentConfig(std::mt19937& rng) const
  {
    std::vector<double> lo(chain.getNrOfJoints()), hi(chain.getNrOfJoints());
    for (unsigned int i = 0; i < chain.getNrOfJoints(); ++i)
    {
      lo[i] = unbounded(i) ? -M_PI : lb(i);
      hi[i] = unbounded(i) ? M_PI : ub(i);
    }
    for (unsigned int i = 0; i < joint_names.size(); ++i)
    {
      const auto joint = model.getJoint(joint_names[i]);
      if (!joint->mimic || joint->mimic->multiplier == 0.0)
        continue;
      // Same rule as expectMimicCouplings: a mimic whose target is outside the chain is a fixture
      // this helper cannot sample, not something to skip quietly -- skipping it would build a
      // coupling-violating target that the assertion then reports as a solver bug.
      const int j = indexOf(joint->mimic->joint_name);
      if (j < 0)
      {
        ADD_FAILURE() << joint_names[i] << " mimics a joint outside the chain";
        return KDL::JntArray(chain.getNrOfJoints());
      }
      double a = (lo[i] - joint->mimic->offset) / joint->mimic->multiplier;
      double b = (hi[i] - joint->mimic->offset) / joint->mimic->multiplier;
      if (a > b)  // sign-aware: a negative multiplier swaps the ends
        std::swap(a, b);
      lo[j] = std::max(lo[j], a);
      hi[j] = std::min(hi[j], b);
      // An empty intersection would hand uniform_real_distribution an inverted range, which is
      // undefined behaviour and would surface as a silently garbage target rather than a diagnosis.
      if (lo[j] > hi[j])
      {
        ADD_FAILURE() << joint_names[i] << " and " << joint->mimic->joint_name
                      << " have no jointly satisfiable interval";
        return KDL::JntArray(chain.getNrOfJoints());
      }
    }

    KDL::JntArray q(chain.getNrOfJoints());
    for (unsigned int i = 0; i < joint_names.size(); ++i)
      if (!model.getJoint(joint_names[i])->mimic)
        q(i) = std::uniform_real_distribution<double>(lo[i], hi[i])(rng);
    for (unsigned int i = 0; i < joint_names.size(); ++i)
    {
      const auto joint = model.getJoint(joint_names[i]);
      if (!joint->mimic)
        continue;
      q(i) = joint->mimic->multiplier * q(indexOf(joint->mimic->joint_name)) + joint->mimic->offset;
    }
    return q;
  }
};

void expectWithinLimits(const Fixture& f, const KDL::JntArray& q)
{
  for (unsigned int i = 0; i < q.rows(); ++i)
  {
    if (f.unbounded(i))
      continue;
    EXPECT_GE(q(i), f.lb(i) - 1e-6) << "joint " << f.joint_names[i] << " below its lower limit";
    EXPECT_LE(q(i), f.ub(i) + 1e-6) << "joint " << f.joint_names[i] << " above its upper limit";
  }
}

double positionError(const KDL::Frame& a, const KDL::Frame& b)
{
  return (a.p - b.p).Norm();
}

double rotationError(const KDL::Frame& a, const KDL::Frame& b)
{
  return (a.M.Inverse() * b.M).GetRot().Norm();
}

// Every mimic joint holds multiplier * mimicked + offset. What "the solver respects the coupling"
// means, and the assertion tickets 04 and 05 turn green.
void expectMimicCouplings(const Fixture& f, const KDL::JntArray& q)
{
  for (unsigned int i = 0; i < f.joint_names.size(); ++i)
  {
    const auto joint = f.model.getJoint(f.joint_names[i]);
    if (!joint->mimic)
      continue;
    const int j = f.indexOf(joint->mimic->joint_name);
    ASSERT_GE(j, 0) << f.joint_names[i] << " mimics a joint outside the chain";
    EXPECT_NEAR(q(i), joint->mimic->multiplier * q(j) + joint->mimic->offset, 1e-6)
        << f.joint_names[i] << " must follow " << joint->mimic->joint_name;
  }
}

}  // namespace

// ---------------------------------------------------------------------------------------------
// arm6: a conventional 6-DOF arm, no mimic joints. Keeps the suite honest about the regressions
// the crane (5 active DOF, position-only) cannot show.
// ---------------------------------------------------------------------------------------------

TEST(TracIkLib, Arm6FullPoseRoundTrip)
{
  Fixture f("arm6.urdf", "base_link", "tool_link");
  TRAC_IK::TRAC_IK ik(f.chain, f.lb, f.ub);
  TRAC_IK::Query q = defaultQuery();

  std::mt19937 rng(1);  // test-side determinism: the TARGETS repeat, the solver's search does not
  int solved = 0;
  for (int n = 0; n < kSamples; ++n)
  {
    const KDL::Frame target = f.fk(f.randomConfig(rng));
    KDL::JntArray seed = f.randomConfig(rng), sol;
    if (ik.CartToJnt(seed, target, sol, q) < 0)
      continue;
    ++solved;
    expectWithinLimits(f, sol);
    const KDL::Frame reached = f.fk(sol);
    EXPECT_LT(positionError(target, reached), kPosTol);
    EXPECT_LT(rotationError(target, reached), kRotTol);
  }
  EXPECT_GE(static_cast<double>(solved) / kSamples, kSolveRateFloor)
      << "solved " << solved << " of " << kSamples;
}

TEST(TracIkLib, Arm6PositionOnlyToleranceFreesOrientation)
{
  Fixture f("arm6.urdf", "base_link", "tool_link");
  TRAC_IK::TRAC_IK ik(f.chain, f.lb, f.ub);
  TRAC_IK::Query q = defaultQuery();

  // Infinite rotational tolerance bounds: the three orientation components are free.
  q.tolerance_bounds.rot.x(std::numeric_limits<float>::max());
  q.tolerance_bounds.rot.y(std::numeric_limits<float>::max());
  q.tolerance_bounds.rot.z(std::numeric_limits<float>::max());

  std::mt19937 rng(2);
  int solved = 0;
  for (int n = 0; n < kSamples; ++n)
  {
    const KDL::Frame target = f.fk(f.randomConfig(rng));
    KDL::JntArray seed = f.randomConfig(rng), sol;
    if (ik.CartToJnt(seed, target, sol, q) < 0)
      continue;
    ++solved;
    expectWithinLimits(f, sol);
    // Position must still be met; orientation is explicitly not asserted.
    EXPECT_LT(positionError(target, f.fk(sol)), kPosTol);
  }
  EXPECT_GE(static_cast<double>(solved) / kSamples, kSolveRateFloor)
      << "solved " << solved << " of " << kSamples;
}

TEST(TracIkLib, Arm6ContinuousJointsAreUnbounded)
{
  Fixture f("arm6.urdf", "base_link", "tool_link");
  KDL::JntArray lb, ub;
  TRAC_IK::TRAC_IK ik(f.chain, f.lb, f.ub);
  ASSERT_TRUE(ik.getKDLLimits(lb, ub));
  for (unsigned int i = 0; i < f.joint_names.size(); ++i)
  {
    const bool is_continuous = f.model.getJoint(f.joint_names[i])->type == urdf::Joint::CONTINUOUS;
    EXPECT_EQ(is_continuous, f.unbounded(i)) << "joint " << f.joint_names[i];
  }
}

// ---------------------------------------------------------------------------------------------
// The crane: 9 chain joints, 4 of them mimic joints, 5 active. Today the library has no notion of
// a mimic joint, so it treats all 9 as active. The coupling test below is the RED one ticket 04
// turns green.
// ---------------------------------------------------------------------------------------------

TEST(TracIkLib, CraneChainShape)
{
  Fixture f("crane.urdf", "base_link", "jib_ext_link");
  EXPECT_EQ(f.chain.getNrOfJoints(), 9u) << "the crane chain has 9 joints with variables";
  int mimics = 0;
  for (const auto& name : f.joint_names)
    if (f.model.getJoint(name)->mimic)
      ++mimics;
  EXPECT_EQ(mimics, 4) << "4 of them are mimic joints";
}

TEST(TracIkLib, CraneSolutionRespectsMimicCoupling)
{
  GTEST_SKIP() << "measures the mimic coupling defect; delete this skip in ticket 05";

  Fixture f("crane.urdf", "base_link", "jib_ext_link");
  // TRAP, pinned deliberately: Distance, not Speed. In Speed mode the KDL branch answers in ~1 ms
  // with a solution whose four parallel prismatic joints happen to be equal -- their Jacobian
  // columns are identical and repeated limit clipping collapses them together -- so the coupling
  // looks intact and this test goes green for a reason that has nothing to do with mimic support.
  // Distance collects solutions for the whole budget and its winner violates the coupling outright
  // (up to 0.86 on main_boom_ext_4, measured). Crane coupling tests therefore pin Distance rather
  // than leaning on the shipped default, and no mimic work may accept a green Speed-mode run as
  // evidence.
  TRAC_IK::TRAC_IK ik(f.chain, f.lb, f.ub);
  TRAC_IK::Query q = defaultQuery(TRAC_IK::Distance);

  // A mimic-consistent full configuration, so the target is reachable under the coupling.
  std::mt19937 rng(3);
  const KDL::Frame target = f.fk(f.mimicConsistentConfig(rng));

  // TRAP, pinned deliberately: NOT a zero seed. The four main_boom_ext* joints are parallel
  // prismatic joints with identical Jacobian columns, so from an all-equal seed a pseudo-inverse
  // step moves them by equal amounts and the mimic violation stays invisible, exactly as in Speed
  // mode. An asymmetric seed is what exposes it.
  KDL::JntArray seed = f.randomConfig(rng), sol;
  ASSERT_GE(ik.CartToJnt(seed, target, sol, q), 0) << "no solution for a reachable crane pose";
  EXPECT_LT(positionError(target, f.fk(sol)), kPosTol) << "the 9 free joints do reach the target";
  expectWithinLimits(f, sol);

  // RED until ticket 04: the solver chooses all 9 joints independently, so the coupling is broken.
  expectMimicCouplings(f, sol);
}

// ---------------------------------------------------------------------------------------------
// The query (ticket 03). Timeout, epsilon, solve type, tolerance bounds and the per-call joint
// bounds are a parameter of CartToJnt, not solver state, so one instance answers many questions.
// ---------------------------------------------------------------------------------------------

// A query whose joint bounds are strictly inside the mechanism's: the middle half of every bounded
// joint's range, and [-1, 1] rad for the continuous ones, which have no range to halve. Continuous
// joints are narrowed on purpose -- a rotational joint is continuous for a call exactly when the
// bounds in force are infinite, so a finite pair here must bound it like any other joint.
TRAC_IK::Query narrowedQuery(const Fixture& f, TRAC_IK::SolveType type = TRAC_IK::Speed)
{
  TRAC_IK::Query q = defaultQuery(type);
  q.q_min.resize(f.chain.getNrOfJoints());
  q.q_max.resize(f.chain.getNrOfJoints());
  for (unsigned int i = 0; i < f.chain.getNrOfJoints(); ++i)
  {
    const double quarter = f.unbounded(i) ? 0.0 : (f.ub(i) - f.lb(i)) / 4.0;
    q.q_min(i) = f.unbounded(i) ? -1.0 : f.lb(i) + quarter;
    q.q_max(i) = f.unbounded(i) ? 1.0 : f.ub(i) - quarter;
  }
  return q;
}

TEST(TracIkLib, QueryJointBoundsNarrowTheSearchWithoutChangingTheMechanism)
{
  Fixture f("arm6.urdf", "base_link", "tool_link");
  TRAC_IK::TRAC_IK ik(f.chain, f.lb, f.ub);
  const TRAC_IK::Query q = narrowedQuery(f);

  // Targets are taken from configurations inside the narrowed box, so they stay reachable under it.
  std::mt19937 rng(21);
  int solved = 0;
  for (int n = 0; n < 40; ++n)
  {
    KDL::JntArray inside(f.chain.getNrOfJoints());
    for (unsigned int i = 0; i < f.chain.getNrOfJoints(); ++i)
      inside(i) = std::uniform_real_distribution<double>(q.q_min(i), q.q_max(i))(rng);
    const KDL::Frame target = f.fk(inside);
    // Seeded from OUTSIDE the box on purpose: a seed inside it would leave the first Newton step
    // inside whether or not the query's bounds were honoured, and the test would pass for nothing.
    KDL::JntArray seed = f.randomConfig(rng), sol;
    if (ik.CartToJnt(seed, target, sol, q) < 0)
      continue;
    ++solved;
    for (unsigned int i = 0; i < f.chain.getNrOfJoints(); ++i)
    {
      EXPECT_GE(sol(i), q.q_min(i) - kEps) << "joint " << f.joint_names[i] << " below the query's bound";
      EXPECT_LE(sol(i), q.q_max(i) + kEps) << "joint " << f.joint_names[i] << " above the query's bound";
    }
  }
  EXPECT_GT(solved, 0) << "the narrowed box must still admit solutions";

  // The mechanism is untouched: getKDLLimits still answers with what the constructor was given.
  KDL::JntArray lb, ub;
  ASSERT_TRUE(ik.getKDLLimits(lb, ub));
  for (unsigned int i = 0; i < f.chain.getNrOfJoints(); ++i)
  {
    EXPECT_DOUBLE_EQ(lb(i), f.lb(i));
    EXPECT_DOUBLE_EQ(ub(i), f.ub(i));
  }
}

TEST(TracIkLib, OneInstanceAnswersQueriesThatDisagree)
{
  Fixture f("arm6.urdf", "base_link", "tool_link");
  TRAC_IK::TRAC_IK ik(f.chain, f.lb, f.ub);

  std::mt19937 rng(22);
  const KDL::JntArray goal = f.randomConfig(rng);
  const KDL::Frame target = f.fk(goal);
  KDL::JntArray seed = f.randomConfig(rng);

  // Three queries in a row on one instance, each changing something the constructor used to own:
  // the solve type, the joint bounds (which rebuild the inner solvers and reclassify the continuous
  // joints), and then back again. Every one must be answered on its own terms -- nothing may
  // survive from the query before it.
  for (const TRAC_IK::Query& q : { defaultQuery(), narrowedQuery(f, TRAC_IK::Distance), defaultQuery(TRAC_IK::Distance) })
  {
    KDL::JntArray sol;
    if (ik.CartToJnt(seed, target, sol, q) < 0)
      continue;  // a single sample may legitimately fail; a wrong answer may not
    EXPECT_LT(positionError(target, f.fk(sol)), kPosTol);
    EXPECT_LT(rotationError(target, f.fk(sol)), kRotTol);
    expectWithinLimits(f, sol);
  }
}

// ---------------------------------------------------------------------------------------------
// arm7 (wayfinder ticket 22): a redundant 7R arm. Against a full-pose goal its 6x7 Jacobian has a
// one-dimensional null space, a third regime the suite lacked -- the crane is rank-deficient and
// arm6 is square. Redundancy is what TRAC-IK's own audience has.
// ---------------------------------------------------------------------------------------------

TEST(TracIkLib, Arm7FullPoseRoundTrip)
{
  Fixture f("arm7.urdf", "base_link", "tool_link");
  ASSERT_EQ(f.chain.getNrOfJoints(), 7u);
  TRAC_IK::TRAC_IK ik(f.chain, f.lb, f.ub);
  TRAC_IK::Query q = defaultQuery();

  std::mt19937 rng(7);
  int solved = 0;
  for (int n = 0; n < kSamples; ++n)
  {
    const KDL::Frame target = f.fk(f.randomConfig(rng));
    KDL::JntArray seed = f.randomConfig(rng), sol;
    if (ik.CartToJnt(seed, target, sol, q) < 0)
      continue;
    ++solved;
    expectWithinLimits(f, sol);
    const KDL::Frame reached = f.fk(sol);
    EXPECT_LT(positionError(target, reached), kPosTol);
    EXPECT_LT(rotationError(target, reached), kRotTol);
  }
  EXPECT_GE(static_cast<double>(solved) / kSamples, kSolveRateFloor)
      << "solved " << solved << " of " << kSamples;
}

TEST(TracIkLib, Arm7PositionOnlyToleranceFreesOrientation)
{
  Fixture f("arm7.urdf", "base_link", "tool_link");
  TRAC_IK::TRAC_IK ik(f.chain, f.lb, f.ub);
  TRAC_IK::Query q = defaultQuery();

  q.tolerance_bounds.rot.x(std::numeric_limits<float>::max());
  q.tolerance_bounds.rot.y(std::numeric_limits<float>::max());
  q.tolerance_bounds.rot.z(std::numeric_limits<float>::max());

  std::mt19937 rng(8);
  int solved = 0;
  for (int n = 0; n < kSamples; ++n)
  {
    const KDL::Frame target = f.fk(f.randomConfig(rng));
    KDL::JntArray seed = f.randomConfig(rng), sol;
    if (ik.CartToJnt(seed, target, sol, q) < 0)
      continue;
    ++solved;
    expectWithinLimits(f, sol);
    EXPECT_LT(positionError(target, f.fk(sol)), kPosTol);
  }
  EXPECT_GE(static_cast<double>(solved) / kSamples, kSolveRateFloor)
      << "solved " << solved << " of " << kSamples;
}

// The self-motion witness: one target, many seeds, genuinely different configurations that all
// reach it. This is the property ticket 07's "walk the candidate list against the validity
// callback" leans on and neither existing fixture has (the crane's spare DOF is a coupling, and
// arm6's square Jacobian gives isolated solutions only).
TEST(TracIkLib, Arm7HasANullSpaceOfSolutions)
{
  Fixture f("arm7.urdf", "base_link", "tool_link");
  TRAC_IK::TRAC_IK ik(f.chain, f.lb, f.ub);
  TRAC_IK::Query q = defaultQuery();

  std::mt19937 rng(9);
  const KDL::Frame target = f.fk(f.randomConfig(rng));

  std::vector<KDL::JntArray> found;
  for (int n = 0; n < 20; ++n)
  {
    KDL::JntArray seed = f.randomConfig(rng), sol;
    if (ik.CartToJnt(seed, target, sol, q) < 0)
      continue;
    ASSERT_LT(positionError(target, f.fk(sol)), kPosTol);
    ASSERT_LT(rotationError(target, f.fk(sol)), kRotTol);
    found.push_back(sol);
  }
  ASSERT_GE(found.size(), 5u) << "the redundant arm should reach one pose from most seeds";

  double widest = 0.0;
  for (size_t a = 0; a < found.size(); ++a)
    for (size_t b = a + 1; b < found.size(); ++b)
    {
      double d = 0.0;
      for (unsigned int i = 0; i < found[a].rows(); ++i)
        d = std::max(d, std::fabs(found[a](i) - found[b](i)));
      widest = std::max(widest, d);
    }
  EXPECT_GT(widest, 0.1) << "distinct solutions for one pose; widest joint spread " << widest;
}

// ---------------------------------------------------------------------------------------------
// mimic_arm (wayfinder ticket 05): the commonest mimic robot on earth -- one revolute mimic at a
// negative multiplier and a nonzero offset, whose own limits are tighter than its mimicked joint's
// map onto. The crane covers "prismatic, x1, +0" and nothing else, so a sign error in the bound
// mapping or in the folded Jacobian is invisible without this fixture.
// ---------------------------------------------------------------------------------------------

TEST(TracIkLib, MimicArmChainShape)
{
  Fixture f("mimic_arm.urdf", "base_link", "tool_link");
  ASSERT_EQ(f.chain.getNrOfJoints(), 4u) << "4 chain joints with variables, 3 of them active";

  const int mimic = f.indexOf("j3");
  const int mimicked = f.indexOf("j2");
  ASSERT_GE(mimic, 0);
  ASSERT_GE(mimicked, 0);
  const auto coupling = f.model.getJoint("j3")->mimic;
  ASSERT_TRUE(static_cast<bool>(coupling));
  EXPECT_EQ(coupling->joint_name, "j2");
  EXPECT_DOUBLE_EQ(coupling->multiplier, -0.5) << "negative on purpose: the crane's are all +1";
  EXPECT_DOUBLE_EQ(coupling->offset, 0.3) << "nonzero on purpose: the crane's are all 0";
  EXPECT_GT(mimic, mimicked) << "the mimic joint sits downstream of the joint it follows";

  // The tightening this fixture exists to make bite: j2's declared limits map onto an interval
  // wider than j3's own, so j2's effective range is strictly narrower than what the URDF declares.
  const double mapped_lo = (f.ub(mimic) - coupling->offset) / coupling->multiplier;  // multiplier < 0
  const double mapped_hi = (f.lb(mimic) - coupling->offset) / coupling->multiplier;  // so ends swap
  EXPECT_GT(mapped_lo, f.lb(mimicked)) << "j3's lower limit must tighten j2 from below";
  EXPECT_LT(mapped_hi, f.ub(mimicked)) << "j3's upper limit must tighten j2 from above";
}

TEST(TracIkLib, MimicArmPositionOnlyRoundTrip)
{
  Fixture f("mimic_arm.urdf", "base_link", "tool_link");
  TRAC_IK::TRAC_IK ik(f.chain, f.lb, f.ub);
  TRAC_IK::Query q = defaultQuery();

  // Three active joints against a three-dimensional position goal: orientation is left free, so the
  // query stays solvable once the coupling is enforced and the solver has 3 variables, not 4.
  q.tolerance_bounds.rot.x(std::numeric_limits<float>::max());
  q.tolerance_bounds.rot.y(std::numeric_limits<float>::max());
  q.tolerance_bounds.rot.z(std::numeric_limits<float>::max());

  std::mt19937 rng(11);
  int solved = 0;
  for (int n = 0; n < kSamples; ++n)
  {
    const KDL::Frame target = f.fk(f.mimicConsistentConfig(rng));
    KDL::JntArray seed = f.randomConfig(rng), sol;
    if (ik.CartToJnt(seed, target, sol, q) < 0)
      continue;
    ++solved;
    expectWithinLimits(f, sol);
    EXPECT_LT(positionError(target, f.fk(sol)), kPosTol);
  }
  EXPECT_GE(static_cast<double>(solved) / kSamples, kSolveRateFloor)
      << "solved " << solved << " of " << kSamples;
}
